mofacts/client/views/profileAudioToggles.html, mofacts/public/styles/main.css
bounding box with instruction text for speech recognition toggles
=> instruction box

mofacts/client/views/contentGeneration.html, mofacts/client/views/contentGeneration.js, mofacts/server/methods.js
Added owner and date created info to template dropdown in content gen, added createdAt property to new collection docs in TDFs - will update DB in prod with accurate dates for TDFs from content generation and default dates for others.
=> create dates on tdfs, owner and date info on template dropdown

mofacts/server/lib/DynamicTdfGenerator.js
check that sub TDF order groups exist in stimulus file w/ 5 or more
=> Ordergroup criteria

mofacts/client/lib/plugins.js, mofacts/client/views/contentGeneration.html, mofacts/client/views/contentGeneration.js
=> multi select content gen items

mofacts/client/views/contentGeneration.css, mofacts/client/views/contentGeneration.html
=> answers in content gen table

mofacts/client/views/instructorReporting.js
=> clear table on progress load

mofacts/client/views/experiment/card.js
Fixes issue #279 by adding a pausedLocks check to voice_stop
=> Issue 279: Make it so audio input obeys pausedLocks session variable 

mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/dialogueUtils.js, mofacts/client/views/home/profile.js, mofacts/client/views/home/profileAudioToggles.css, mofacts/client/views/home/profileAudioToggles.html, mofacts/client/views/home/profileAudioToggles.js
Implements UI changes requested in issue #260.
Allows the user to set Question and Feedback TTS independently.
Adds independent volume slider for Question and Feedback TTS.
=> Issue 260: Audio settings

mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js
#269 
-Reproduced bug by adding text and a second blank to testStim.json and dropping the database in postgres and re-initializing. This concatenated clozeText and text on the first run of a given card. Unsure if related.
Fix: reordering the condition statement on line 1225 in card.js
=> Issue 269: Sentence incomplete

mofacts/common/Definitions.js
fixes #273 by changing semester to FA_2021 in definitions
=> Issue 273: Can't assign new content

mofacts/client/views/experimentReporting/studentReporting.html, mofacts/client/views/experimentReporting/studentReporting.js
=> Issue 265: cosmetic changes to new progress reports

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/lib/router.js, mofacts/client/views/experiment/answerAssess.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/instructions.js, mofacts/client/views/experiment/unitEngine.js, mofacts/client/views/experimentReporting/dataDownload.js, mofacts/client/views/experimentSetup/contentGeneration.js, mofacts/client/views/experimentSetup/contentUpload.js, mofacts/client/views/experimentSetup/tdfAssignmentEdit.js, mofacts/client/views/home/profile.js, mofacts/client/views/home/profileSouthwest.js, mofacts/client/views/turkWorkflow.js, mofacts/common/DynamicTdfGenerator.js, mofacts/server/conversions/convert.js, mofacts/server/methods.js
-Removed the long calls to json data
-Removed calls to length 1 arrays that were a side effect of xml2json conversion. 
closes: #110 and #289
=> Issue 110: Switch to all JSON data for TDFs/Stims

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experimentReporting/studentReporting.html, mofacts/client/views/experimentReporting/studentReporting.js, mofacts/server/methods.js
#340 
-Design Changes
-Remove old progress bars
-Fixed bug where time wasn't being displayed due to time being cleared by function call
-Added filter for hidden items
=> Issue #340 progress report cleanup

mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js
#244 
-Removed all references from setspec for clustermodel tag.
=> Issue 244 removed clustermodel tag and references

mofacts/.meteor/packages, mofacts/.meteor/versions, mofacts/client/lib/router.js, mofacts/client/views/experimentSetup/assetUpload.html, mofacts/client/views/experimentSetup/assetUpload.js, mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js, mofacts/client/views/userAdmin.html, mofacts/common/Collections.js, mofacts/server/methods.js
=> iss150: Asset Uploader

mofacts/client/views/experimentReporting/instructorReporting.js, mofacts/server/methods.js
=> Issue 363: Teacher progress reports not displaying classname

mofacts/client/index.html, mofacts/client/index.js, mofacts/client/lib/router.js, mofacts/client/views/experiment/card.js, mofacts/client/views/login/signIn.js, mofacts/client/views/login/signInOauth.js, mofacts/client/views/login/signInSouthwest.js, mofacts/client/views/login/signUp.js, mofacts/client/views/tabwarning.html
=> Issue #367: logout other browsers with the same user

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js
Content loading inter-trial message is now configurable with the intertrialmessage delivery param. Default is ""
Closes: #369
=> Issue 369: Content Loading

mofacts/client/index.html, mofacts/client/index.js, mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js
=> Issue 365: added button to profile for wiki

mofacts/client/views/home/profile.html
=> Issue 381: move tts and feedback menu

mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js
=> Issie 362: Centered speaker icon

mofacts/client/views/home/profileAudioToggles.html
Changed the minimum value of question tts volume slider to match feedback
closes #378
=> Issue 378: Volume Change in TTS

mofacts/server/methods.js
#397  Hintlevel addition was making the query return null. Might fix other issues as well.
=> Issue 397: fixed hintLevel query to fix issue

mofacts/client/views/experimentReporting/studentReporting.js
=> Issue 397: progress reports - changed a variable

mofacts/server/lib/AllenNLP.js, mofacts/server/lib/ClozeAPI.js, mofacts/server/lib/TutorialDialogue.js
closes 392, integrating @aolney
=> Issue 392: incorporate server lib changes

mofacts/client/views/login/signInOauth.js
Closes #377. Changes google auth method to redirect instead of a popup.
=> Issue 377: change google login mode to mobile friendly

mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js
- Removed unnecessary hintlevel calculations causing 4x extra calculations to be run for each card in probability calculations
- Added unit engine function to allow for probability calculations to occur during incorrect answer timeout for learning sessions
Closes: #383
=> Issue 383: Card Calculation Optimization

mofacts/client/views/experiment/card.js
=> Issue 380: Get rid of intersitials when not needed

mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/instructions.html
=> Issue 412: Instructions: appears on the top of the screen

mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js
added skip unit button for admins and teachers
closes #413
=> Issue 413: Unit Skip Button

mofacts/client/views/login/signInSouthwest.html, mofacts/client/views/login/signInSouthwest.js
Added a check for if a section exists in a class. If not then it just shows the class name without the hyphen
closes: #410
=> Issue 410: Odd Extra Hyphen

mofacts/client/views/experiment/card.js
=> Iss416 Added check for unitinstructions and unitinstructionsquestion

mofacts/client/views/experimentSetup/contentUpload.html, mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
Case: 
Go to content uploader, click the download button under uploaded files.
closes #414
=> Issue 414: added download option

mofacts/client/views/experiment/card.html
=> Issue 428: made button into smaller link

mofacts/client/lib/router.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/instructions.html, mofacts/client/views/experiment/instructions.js
Fixes #431 by performing instructions logic without displaying it.
=> Issue 431: fixed routing error

mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js
=> Issue 425: added check for audio playing before trying to record

mofacts/client/views/experimentReporting/instructorReporting.html, mofacts/client/views/experimentReporting/instructorReporting.js, mofacts/server/methods.js
- changed time drop down to a number input field 
- hides users who have not begun practice until after date defined by teacher
- fixed componentstate update querey causing component state to never be overwritten, causing time to increase factorialy
- changed practice time querey to get a users full practice time instead of response duration.
closes #426
=> Issue 426: Teacher report bugs and refinement

mofacts/client/index.js, mofacts/client/views/home/profileDialogueToggles.js, mofacts/private/tdf/testTdf.json
=> Issue 423: Feedback settings button doesnt work on Instructions page

mofacts/client/views/experiment/unitEngine.js
=> Issue 440: findMinProbDistCard bug

mofacts/client/views/experiment/card.js
Added countdown timer for dialogue when the user is incorrect.
=> Issue 446: Countdown timer for simple and refutational feedback

mofacts/client/views/experiment/unitEngine.js
hintLevel probabilities was not being passed to selectCard, which it now is. If hintLevelProbabilites return less than 0, null, or NaN, an error will be thrown,
=> Issue 457: fixed problems with probabilities

mofacts/client/views/experiment/unitEngine.js
- Reintroducing debugLog to probability function from feature freeze. Closes #458
=> Issue 458: added debug to probability function

mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js
Moved countdown timer outside of feedback
Fixed issue causing innerHTML error
Fixed issue causing feedback to be reset on refutation. 
closes #463
=> Issue 463: Countdown Timer Clearing Refutational Feedback

mofacts/client/views/home/profileDialogueToggles.html
=> Issue 466: Questions misspelled

mofacts/client/views/experimentReporting/studentReporting.html, mofacts/client/views/experimentReporting/studentReporting.js, mofacts/server/methods.js
=> progress report redux

mofacts/client/views/experiment/unitEngine.js
=> named something wrong

db/initTables.sql, mofacts/client/index.js, mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experimentReporting/dataDownload.js, mofacts/client/views/login/signInSouthwest.js, mofacts/common/Definitions.js, mofacts/server/experiment_times.js, mofacts/server/methods.js, mofacts/server/orm.js
- Fixed bug causing data to not populate file
- Added `Entry_Point` column in `history` table to log how a user entered the application (null if not through southwest)
- Added `Entry_Point` data too data download
closes #471
=> Issue 471: Data Download Fails and New Data for Download

mofacts/client/views/experimentReporting/studentReporting.js, mofacts/server/methods.js
fixed #490 
The query was returning information based on the unfiltered last 30 trials, instead of the last 30 based off of that particular user and tdf.
=> Iss490: Progress report not showing up after 30 practices

mofacts/client/views/login/signInSouthwest.js
=> Issue 494: Test logins not showing

mofacts/client/views/experiment/card.js
=> Issue 497: Crash on restart of John Doe

mofacts/client/views/experimentReporting/studentReporting.html, mofacts/client/views/experimentReporting/studentReporting.js
Progress report wasnt showing because the draw function was looking for items that havent been enabled. Changed blaze calls to hide/show so that dashboard is always available for rendering.
closes #498
=> Issue 498: Progress Report Not Showing

mofacts/package-lock.json, mofacts/package.json
removed node-sass package that was unused. 
Node-sass was using outdated dependencies that have security vulnerabilities.
=> Issue 389: Dependabot issues

mofacts/client/views/login/signInSouthwest.js
Added emails to test logins
removed test teacher accounts from server when not accessing test address. 
closes #506
=> Issue 506: Setup login ids for instructors 

mofacts/client/views/experiment/unitEngine.js
=> Issue 508: added answerText to probability function access

mofacts/client/index.js
=> Issue 510: first instructions not showing

mofacts/client/views/home/profile.html, mofacts/client/views/home/profileSouthwest.js
=> Iss526: Icon legend

mofacts/client/views/home/profileAudioToggles.html
=> Iss525: Text change

mofacts/client/views/home/profileSouthwest.js
=> updated audiohtml

mofacts/client/views/experiment/unitEngine.js
=> iss532: Added check for syllable dataset if answer is not in dictionary

mofacts/client/views/experimentReporting/studentReporting.html
=> Iss545: tooltip hint

mofacts/server/experiment_times.js
=> Iss539: fixed extra lines

mofacts/client/views/experimentReporting/instructorReporting.html
=> iss540: remove all classes functionality in instructor reporting

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experimentReporting/studentReporting.js
=> Iss547: Rounded Minutes

mofacts/client/views/experiment/card.js
=> Iss542: Removed alert, added prompt.

mofacts/client/views/home/profileSouthwest.js
=> Issue 550: fixed data fields

mofacts/client/views/home/profileSouthwest.html, mofacts/client/views/home/profileSouthwest.js
=> Iss531: fixed legend icons for profilesouthwest

mofacts/client/views/experimentSetup/classEdit.js
gives an alert box for blanks
fixes #560
=> iss560: cant have blank sections or classes

mofacts/server/methods.js
SQL UPDATE call was causing all items to be overwritten with the last item in a stim file because it didnt have a WHERE clasue. 
Added removal of items during overwrite if new stim file is shorter than previous. 
Will require db dump to clean up errors in db caused by bug. 
closes #556
=> Issue 556: When posting content stim files are not accepted

mofacts/client/views/experimentSetup/contentUpload.html, mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
=> Iss561: Add delete buttons as a temporary fix for #556

mofacts/client/views/experimentReporting/dataDownload.js, mofacts/server/methods.js
Was missing an await call for async function.
Data export function was expecting single file name but was given list of file names. Updated calling function to only pass file names one by one. 
Closes #541
=> Issue 541: data download all function doesn't produce anything

mofacts/client/views/experiment/card.js
=> Iss544 extra recording lock

mofacts/client/views/experimentReporting/studentReporting.html, mofacts/client/views/experimentReporting/studentReporting.js
=> issue 467: student reporting

mofacts/client/views/home/profileSouthwest.js, mofacts/server/methods.js
Fixes #559 
The sectionId wasn't being passed along to the tdf selection, forcing a display of all sections TDFs.
=> Iss559: passed section to profile

mofacts/client/views/experimentSetup/tdfAssignmentEdit.html
=> Issue 566: added filename to assignments

mofacts/client/views/experiment/answerAssess.js, mofacts/client/views/experiment/card.js
=> Iss536: The syllablized answer was allowing blanks to be correct.

mofacts/client/views/experiment/card.js
If refutationstudy isnt defined it will default to reviewstudy.
=> Issue 571: Not answering yes broke it

mofacts/client/index.js, mofacts/client/lib/sessionUtils.js, mofacts/client/views/home/profileSouthwest.js, mofacts/client/views/login/signInSouthwest.js
=> Issue 589: edited to fix southwest home button

mofacts/client/views/experiment/answerAssess.js
=> Issue 581: Please answer every question

mofacts/client/views/experiment/card.js
Reverts memphis-iis/mofacts-ies#578
=> Revert "Iss544 extra recording lock"

mofacts/client/views/experiment/card.js
=> Iss579: Comandeered Back Button

mofacts/client/views/experimentReporting/instructorReporting.js
Detects nan (not the bread) and if nan, then do nothing
Fixes #591
=> Iss591: detects nan

mofacts/client/views/experiment/answerAssess.js
dispAnswer out of scope causing dispAnswer to be undefined on blank response. 
closes #598
=> Issue 598: Blank response crashes system

mofacts/client/views/experimentReporting/studentReporting.html
=> Issue 607: grammar check

mofacts/client/views/experiment/card.js
=> Issue603: Added Regex to filter HTML

mofacts/client/views/home/profileSouthwest.js
=> Iss608: checked for reload

mofacts/server/methods.js
=> edited query

mofacts/client/views/experiment/card.js
Review time was set up to report during refutation and not during other times causing this bug
closes #624
=> Issue 624: Not reporting the review time

db/initTables.sql, mofacts/client/views/experiment/card.js, mofacts/server/methods.js, mofacts/server/orm.js
=> Iss635: added item removal to history

db/initTables.sql, mofacts/client/views/experiment/card.js, mofacts/server/methods.js, mofacts/server/orm.js
=> Iss622: added field for hint sylls displayed

mofacts/server/experiment_times.js, mofacts/server/methods.js
added check for multi-tdf download to remove excess headers
closes #620
=> Issue 620: Data txt file is duplicating lines

mofacts/client/views/experiment/card.html
=> Issue 653: new drop message

mofacts/client/views/experiment/unitEngine.js
Fixes #654, was using an unneeded variable that didn't get passed to hintSylls calculation
=> Issue 654: Changed Logic

mofacts/client/views/experimentSetup/contentUpload.html, mofacts/client/views/experimentSetup/contentUpload.js
=> Iss651: dissalowed deleting stim sets of others

mofacts/client/views/login/signIn.js, mofacts/client/views/login/signInOauth.js, mofacts/client/views/login/signInSouthwest.js, mofacts/client/views/login/signUp.js, mofacts/server/methods.js
loginExpirationInDays is a system setting, not an account setting. It was throwing errors because it was being set multiple times. 
Moved to server side so that it is only called on startup 
closes #665
=> Issue 665: Fail to log in

mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/dialogueUtils.js
History was reporting time before refutation/review timeout could complete causing history time to be shorter than component state. 
Dialogue time was not being recorded. added this. 
closes #672
=> Issue 672: History not reporting correct time

mofacts/client/views/experiment/card.js
=> Issue 658: fixed hintIndeces

mofacts/client/views/experiment/card.js
Sectionname not always defined. Causing crashing when writing to history. 
closes #674
=> Issue 674: Cant resume

db/initTables.sql, mofacts/client/views/experiment/card.js, mofacts/server/methods.js, mofacts/server/orm.js
Updated db times to reflect #677.
Removed unused columns.
closes #677
=> Issue 677: Times Wrong

mofacts/client/views/experiment/card.js, mofacts/private/stims/exampleStim.json
=> Issue 675: Stopped countdown timer if question removed

mofacts/client/views/experimentReporting/studentReporting.html
=> Iss683: added labels for speed of learning

mofacts/client/index.js, mofacts/client/lib/router.js, mofacts/client/views/experiment/card.js, mofacts/client/views/login/signInSouthwest.js
Fixes #649
If back button is pushed on signInSouthwest during any time, it redirects to the beginning logic of signInSouthwest
=> Issue 649: added restricted routes

mofacts/client/views/experiment/unitEngine.js
=> Issue 676: changed where hintlevel history is coming from

mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js
Added shortcut for question report timeout.
closes #675
=> Issue 675: After removing the item, it continues to make me wait for the next trial

mofacts/client/views/experimentReporting/studentReporting.js
=> Issue 684: changed rouding to two decimals

mofacts/server/experiment_times.js
=> Issue 678: Duplicated columns now missing

mofacts/client/views/experiment/unitEngine.js
=> Issue 688: fixes spaces and filling in all blanks

mofacts/client/views/experiment/card.js
=> Issue 694: Countdown timer disappears on refutation

mofacts/server/methods.js
fixes #700 syllables are cached on tdf upload
=> Issue 700: syllables happen on upload

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.js
=> Iss698: Write studentPerformance to session variable

mofacts/client/views/experiment/unitEngine.js
Blanks were still being added per syllable. Added loop that replaces ____ in answer with fixed length blanks
Closes: #702
=> Issue 702: Fill in lengths are weird

mofacts/client/views/experiment/card.js, mofacts/common/Definitions.js, mofacts/server/methods.js
Reworked item reporting to capture full trial duration
Changed how removed items is reported in history to preserve outcome
Fixed progress report to show progress made on reported items
closes #703 
closes #705
=> Issue 703 & 705

mofacts/client/lib/currentTestingHelpers.js
Reverts memphis-iis/mofacts-ies#712
=> Revert "iss711: removed extraneous ||"

mofacts/client/views/experiment/unitEngine.js, mofacts/server/methods.js
Syllable database had a one time error that caused hint level to not be calculated and saved. This caused component state to not save current data. If this happens there is no way to see how long a user was practicing a trial.
Added an error handle that reports the current error stack to developers and kicks the user from the trial. Also added a verification process for the stim syllable upload that throws an error after 3 failed attempts to upload the syllable data. 
closes #711
=> Issue 711: Component state not saving

mofacts/server/methods.js
stimsseen was not accounting for dropped stims. 
closes #725
=> Issue 725: Removed items not removed from fixe dial... note 63 of 59

mofacts/client/views/experiment/unitEngine.js, mofacts/server/methods.js
Fixes #722, reloads syllable cache on every upload.
=> Iss722: reload syll cache on every upload

mofacts/client/views/experiment/unitEngine.js, mofacts/client/views/experimentReporting/studentReporting.html, mofacts/client/views/experimentReporting/studentReporting.js, mofacts/server/methods.js
Added console logs for all trials, last 30, and last 60.
Removed dropping of removed items from the progress report.
Dropped items only appear in the mastered items gague.
Progress report only reports on learning sessions. Previously included assessments.
=> Issue 733: Student Report

mofacts/client/views/experimentReporting/instructorReporting.css, mofacts/client/views/experimentReporting/instructorReporting.html, mofacts/client/views/experimentReporting/instructorReporting.js, mofacts/server/methods.js
Removed column and input as requested
Updated the query that fetches student data for instructors to allow the table to update based on date provided in the input.
closes #739
=> Issue 739: Instructor report date filter doesn't do what it is supposed to

mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js
Index calculations were still not running synchronously with the review timeout. Now they are synchronous. 
Review timeout can be bottle-necked by index calculations if they take too long (i.e index calculations take 3 seconds but review timeout takes 2 means that the system wont progress for an extra second).
closes #752
=> Issue 752: Review timeout taking too long

mofacts/client/views/experiment/unitEngine.js
Fixes #754  The priority for selecting next card was card probability then hint probability, now it's hint probability only, where available.
=> Issue 754: changed priority of calculate indecies

mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js, mofacts/client/views/home/profile.js
One function call was used to get the question information for a cluster. This function included a heavy for loop that was being called inside double and triple nested for loops. After optimization the index calculations run 25x faster. 
- Old version:
- New version: 
closes #759
=> Issue 759: Optimized index calculations

mofacts/server/methods.js, scripts/mup-deploy.sh
Methods should never be declared in an aync function because they become unavailable on deployments @aolney 
--Note to Andrew:
This was the reason for your docker failure and my meteor up failures.
=> Isss768: Moved methods

mofacts/client/views/experiment/card.js
=> Issue 765: System reads '&nbsp;' instead of saying 'blank'

mofacts/client/views/experimentSetup/contentUpload.css, mofacts/client/views/experimentSetup/contentUpload.html, mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
Syllable cache and stim file getting out of sync is causing the trials to crash. This would happen when a stim file is updated through the file uploader. Syllable cache is not checked/updated with this new data. 
Now system clears the syllable cache by stim id and re-upload the syllable cache from the new stim file. 
closes #763
=> issue 763: Hints not working

mofacts/client/views/experimentReporting/dataDownload.js, mofacts/client/views/userAdmin.html, mofacts/client/views/userAdmin.js, mofacts/server/experiment_times.js, mofacts/server/methods.js
Data download files were too large and Meteor was not passing it from the server back to the client.
- added API routes on server for data download
- added secret keys for admins and teachers
- admins can reset all secret keys
- teachers will not need to give secret keys to download files (handled by system)
- secret key is required to generate the file. 
- data file generation is now 25x faster.
closes #782
=> Issue 782: All tdf download button broken by new tdf

mofacts/client/index.js, mofacts/client/views/home/profileAudioToggles.html, mofacts/client/views/home/profileAudioToggles.js
Disables SR for safari 
closes #787
=> Issue 787: Speech Recognition not working on safari

mofacts/client/views/experimentSetup/contentUpload.js
=> Issue 802: Dowloading Chapter12c tdf from the interface with the download button

mofacts/common/Definitions.js, mofacts/server/orm.js
Dialogue data was not being passed to the file for download. Same with feedback type and hint level. These are fixed now.
closes #632
=> Issue 632: Dialogue trials in data

mofacts/client/index.html, mofacts/private/tdf/testTdf.json
changed help button to allow html
closes #789
=> Issue: 789: "Help" button part 2

mofacts/client/views/experiment/card.js
A feature of Safari is that it will not allow audio to autoplay. To fix this I've added MDN's speech synthesis as a backup to the google TTS call. If the TTS call fails for any reason (safari or otherwise) TTS can be handled by MDN. 
closes #786
=> Issue 786: Safari TTS bug

mofacts/client/views/experiment/answerAssess.js
=> Check for answer repetition

mofacts/common/Collections.js
Fixes #806 
The GIF extension was not allowed. @MegaGeese is out on leave this week, so if its a priority, we can code review it together, or just trust me @imrryr
=> Issue 806: added gif upload option

mofacts/client/lib/router.js, mofacts/client/views/login/resetPassword.html, mofacts/client/views/login/resetPassword.js, mofacts/client/views/login/signIn.html, mofacts/package-lock.json, mofacts/server/methods.js
=> Iss794: added password reset function for not Oauth users

mofacts/client/views/experimentSetup/assetUpload.html, mofacts/client/views/experimentSetup/assetUpload.js
=> Uploader will now accept multiple assets to be selected

mofacts/client/index.js, mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.js, mofacts/package-lock.json
TTS pauses when the help button is pressed and resumes when the modal is closed
Help modal can no longer be opened during refutation. 
closes #816
=> Issue 816: Trial runs behind help and trial runs after returning home

mofacts/client/views/experiment/card.js
timer uses correct time for timeout on timeout
closes #818
=> Issue 818: Timer wrong

mofacts/client/views/experimentSetup/contentUpload.js
changed file upload to use utf-8 encoding
closes #830
=> Issue 830: Greek file encoding

mofacts/client/views/experiment/card.js
fixed item removal stopping trial
closes #832
=> Issue 832: Item removal button stopping trial

mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.js, mofacts/package-lock.json
=> Issue 826: Chapter 6 stops working

mofacts/server/methods.js
Stim Sylls document in mongodb is now removed and regenerated on stim file upload. This prevents the chance for syllables to not be available for trials. 
closes #823
=> Issue 823: Error message about hints

mofacts/client/views/experimentSetup/assetUpload.html, mofacts/client/views/experimentSetup/assetUpload.js, mofacts/common/Collections.js, mofacts/server/methods.js
=> Fixed package uploader

mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.js, mofacts/client/views/home/profile.js, mofacts/client/views/home/profileAudioToggles.html, mofacts/client/views/home/profileAudioToggles.js, mofacts/server/methods.js
Adds the ability to select voices for TTS option. Should also consider giving names to the voices for recognition. 
closes #75
=> Issue 75: Add voice select for TTS

mofacts/client/views/experimentReporting/instructorReporting.css, mofacts/client/views/experimentReporting/instructorReporting.html
=> Issue 127: Fixed Table CSS on Instructor Reporting

mofacts/client/views/experimentReporting/studentReporting.html
=> Adds Main Text To Hover in Progress Report

mofacts/server/methods.js
When uploading a stim file that does not have the same name as an existing stim set, the system assumes it is new and gives it a new stim set id. If this file was to be used with an existing TDF then there was no way for the system to check this. 
Now when overwriting an existing TDF the system will check to make sure the stim file names match and update the stim set id accordingly.
Note: As of now we cannot remove old stims from the database because the item id is used as a foreign key to the history table. 
closes #834
=> Issue 834: Stim and TDF upload mismatch

mofacts/client/lib/router.js, mofacts/client/views/login/signIn.html, mofacts/client/views/login/signIn.js
fixes #857, creates a unfied signin page for non southwest logins
=> Issue 857: unified signin page

mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js, mofacts/private/tdf/testTDF-tags.json
fixes #867
setspec now can have an array "tags" which are filterable using a text box on the enable tdfs dropdown on the profile page.
to set in setspec:
"tags" : ["tag1","tag2"]...
=> Issue 867: added filter mechanism

mofacts/public/styles/main.css
=> Changed CSS Settings

mofacts/server/methods.js
fixes #877 
-triggers upload when there are no tdfs on startup
-removes call to StimSyllables collection, since sylls are being stored in individual TDF documents in TDF collection
-fixes some undefined variable calls
=> Iss877: Fixes Tdf and stim Upload on Start / Package Uploader

mofacts/server/methods.js
=> Issue 879: Rhodes fixed a thing (the tdf visibility problem)

mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
=> Issue 884: No download buttons for tdfs on staging

mofacts/server/methods.js
=> Issue 882: Assets not loading on mofacts

mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js, mofacts/client/views/home/profile.html, mofacts/client/views/home/profileDebugToggles.css, mofacts/client/views/home/profileDebugToggles.html, mofacts/client/views/home/profileDebugToggles.js
=> Adds Debug Menu to Profile

mofacts/server/experiment_times.js, mofacts/server/methods.js
Fixes the data formatting errors on mofacts.
=> Issue 868: Data Download

mofacts/client/views/experiment/card.js, mofacts/package-lock.json
Help button doesn't disable on assessment sessions
closes #855
=> Issue 855: Disabling help causing unneeded flashing

mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/dialogueUtils.js
Question context is retained for dialogue feedback
closes #615
=> Issue 615: Rethink dialogue integration

mofacts/client/views/experiment/card.js, mofacts/client/views/experimentReporting/dataDownload.html, mofacts/client/views/experimentReporting/dataDownload.js, mofacts/server/experiment_times.js, mofacts/server/methods.js
Now save teacher ID on history items so that we can limit data output by id. 
Removed cloze edit history.
Fixed data download for staging.
closes #868
=> Issue 868: Data output

mofacts/client/views/experiment/card.js, mofacts/client/views/login/signIn.js, mofacts/client/views/login/signInOauth.js, mofacts/client/views/login/signInSouthwest.js, mofacts/client/views/login/signUp.js, mofacts/server/methods.js
Entry point data now stored in user profile. Updated every time the user logs in.
=> Issue 903: Entry point data is flaky

mofacts/client/views/experimentSetup/assetUpload.html, mofacts/client/views/experimentSetup/assetUpload.js, mofacts/common/Collections.js, mofacts/server/methods.js
Files aren't being overwritten when uploaded with the same name and by the same author. Causing the system to get overloaded with assets. 
Use subscribe/publish to view assets on the page rather than session variables. 
closes #895
=> Issue 895: Fails to upload assets with files

mofacts/client/views/experiment/unitEngine.js
=> Issue 900: Hints not given on staging

mofacts/common/Definitions.js, mofacts/server/experiment_times.js, mofacts/server/lib/AllenNLP.js, mofacts/server/lib/App.js, mofacts/server/lib/CachedElaboratedFeedback.js, mofacts/server/lib/ClozeAPI.js, mofacts/server/lib/DefinitionalFeedback.js, mofacts/server/lib/Thoth.Json.4.0.0/Encode.js, mofacts/server/lib/fable-library.2.10.2/Double.js, mofacts/server/orm.js
Data output was blanket limited to 256 characters. Some datashop fields can be much larger, added exceptions for these fields 
closes: #901
=> Issue 901: Data output related issues

mofacts/client/lib/router.js, mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/unitEngine.js, mofacts/client/views/experimentReporting/instructorReporting.html, mofacts/client/views/experimentReporting/instructorReporting.js, mofacts/client/views/experimentReporting/studentReporting.html, mofacts/client/views/experimentReporting/studentReporting.js, mofacts/client/views/experimentSetup/classEdit.html, mofacts/client/views/experimentSetup/classEdit.js, mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js, mofacts/client/views/home/profileSouthwest.js, mofacts/client/views/login/signIn.html, mofacts/client/views/login/signIn.js, mofacts/client/views/login/signInSouthwest.js, mofacts/public/styles/main.css, mofacts/server/methods.js
@imrryr  this is a big one
fixes:
-adds support for setspec.duedate (YYYY-MM-DD)
-revamps instructor reporting page to be more in line with meteor development standards
-revamps instructor reporting page to be more streamlined for programmers
-adds filter for due date
-adds exceptions for due dates (added from instructor reporting) by student and tdf
-profile and southwestprofile now has due dates listed on tdf buttons, if applicable
-profile and southwestprofile now disabled overdue tdfs, displays them as unclickable
-regular profile was showing all tdfs, not assigned tdfs to class. this has been fixed.
-fixes bug in /classes/<teacher_username> functionality
-adds notice for due dates in student reporting
=> Iss870: adds functionality for duedates and other fixes

mofacts/client/views/login/signIn.js, mofacts/client/views/login/signInSouthwest.js
Students were not being added to sections on sign in. Fixed now.
=> Issue 910: Teacher report is blank

mofacts/client/views/experiment/unitEngine.js
hintlevel was removed from probability calculation function for whatever reason.
=> Issue 900.2: Hints not given on staging

mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.js
fixed dialogue box staying longer than needed
=> Issue 915: Dialogue text box not clearing after dialogue

mofacts/client/views/experimentSetup/classEdit.html, mofacts/client/views/experimentSetup/classEdit.js
=> Iss922: added section links on classedit page

mofacts/server/methods.js
=> Iss920: fixed teacher reporting time

mofacts/server/experiment_times.js
fixed dynamic stim tags not being as dynamic as expected
=> Issue 926: Data report wrong for stimuli columns

mofacts/client/views/experimentSetup/contentUpload.js
=> Issue 936: Removed check for tdfs to be seen by admin

mofacts/client/lib/router.js
=> Iss931: fixed southwest link logins

db/resetUserData.sh, mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experiment/answerAssess.js
=> Issue 949: Wrong feedback for the no response

mofacts/client/views/experimentReporting/studentReporting.js
=> Iss944: changed source of student reporting time

mofacts/client/views/experimentSetup/assetUpload.html, mofacts/client/views/experimentSetup/assetUpload.js, mofacts/server/methods.js
=> Issue 941/942 Added error feedback for package uploader

mofacts/client/views/experimentReporting/studentReporting.js
=> Iss955: removes extraneous data call for graph

mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js
=> Iss959: comment out profile page exceptions and due dates

mofacts/client/views/experiment/card.js
=> Issue 964: Check for negative latency issue

mofacts/client/views/experimentSetup/assetUpload.js, mofacts/server/methods.js
fix package upload to handle image file upload for tdf
=> Issue 963: Images not appearing in help

mofacts/client/views/experiment/card.js
=> Issue 978: SR using TTS as answer

mofacts/client/index.js, mofacts/client/lib/router.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/instructions.js, mofacts/client/views/experimentReporting/studentReporting.js, mofacts/client/views/home/profile.js, mofacts/client/views/home/profileSouthwest.js, mofacts/client/views/login/resetPassword.js, mofacts/client/views/login/signIn.js, mofacts/client/views/login/signInOauth.js, mofacts/client/views/login/signInSouthwest.js, mofacts/client/views/login/signUp.js, mofacts/server/methods.js
user login mode and login data is stored on the profile instead of session variable now. This allows us to load a user directly back to the right profile page without requiring a relog.
=> Issue 974: Flacky HTML

mofacts/client/views/home/profileSouthwest.js, mofacts/public/styles/main.css
added margins to buttons with css 
fixes #977
=> iss977: added margins to buttons

mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js
Adds search and tag feature. 
@imrryr - 
tags can be put into setspec.tags as an array ["tag1","tag2"]
=> iss986: add tag search feature

mofacts/client/views/experiment/card.js
```js
const afterAnswerFeedbackCallbackWithEndTime = afterAnswerFeedbackCallback.bind(null,
trialEndTimeStamp, trialStartTimestamp, source, userAnswer);
```
Binding the timestamp in this way removes the chance of the timestamp being changed for any given trial. This allows for the trial start timestamp to be changed before the callback for a previous trial fires without effecting the output of the callback.
=> Issue 1005: Bind trial start timestamp to callback

mofacts/server/methods.js
Tdfs without tips could not be processed. 
Closes: #1009
=> Issue 1009: TDF fails to upload

mofacts/client/views/login/signIn.js, mofacts/client/views/login/signInOauth.js, mofacts/client/views/login/signInSouthwest.js, mofacts/client/views/login/signUp.js, mofacts/server/methods.js
Fixed login data not being set for experiment logins
=> Issue 1011: Experiment link not working

mofacts-vagrant-build.sh, mofacts/private/versionInfo.json, mofacts/server/methods.js
Prod version of https://github.com/memphis-iis/mofacts-ies/pull/1013
Deployment Info Emails now include commitID, Build timestamp, branch name, builder, repo URL, and server hostname
=> Issue 1008: more verbose deployment emails (for prod)

mofacts-vagrant-build.sh, mofacts/private/versionInfo.json, mofacts/server/methods.js
Deployment Info Emails now include commitID, Build timestamp, branch name, builder, repo URL, and server hostname
closes #1008
=> More verbose deployment emails

mofacts/client/index.js, mofacts/client/lib/router.js, mofacts/client/views/experiment/instructions.js, mofacts/client/views/home/profile.js, mofacts/client/views/login/signIn.html, mofacts/client/views/login/signIn.js
Fixed profile page flashing before experiment
removed google sign in button from experiment login
fixed bugs preventing experiements from running
=> Issue 1016: Experiment tdf issues (for staging tdf with anatomystims)

mofacts/client/views/experiment/unitEngine.js
Fixed blanks always being put at the begining
=> Staging Issue 1018: Underline in cloze items is misplaced

mofacts/server/experiment_times.js
Admins have access to all data
Teachers have access to data completed in their class or any TDF they upload.
=> Issue 1026: Data not accessible by teacher account that posted tdf

mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js
moved checkbox outside of button
fixed bug requiring reload to show enabled/disabled tdfs
=> Issue 999: Tdfs can't be disabled

mofacts/client/views/experiment/card.js
Prevent card from completing before feedback TTS has concluded.
=> Issue 973: TTS integration with trial timer to prevent cutoff

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experiment/unitEngine.js
Added definable default threshold values. In deliveryParams add `optimalThreshold` as any numeric value to use it. 
closes #1036
=> Issue 1036: Default probability set in deliveryparams

mofacts/client/lib/router.js, mofacts/client/views/adminControls.html, mofacts/client/views/adminControls.js, mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js, mofacts/server/methods.js
Added wrapper function that times all called functions if verbosity allows
Edited serverConsole function to only log at certain verbosity levels
Added admin page that can toggle verbosity levels for server logs between: 
1. Only serverConsole logs 
2. Only function times
3. Both
More functionality can be added to the admin page in the future such as: setting global experiment params, changing site colors, etc.
=> Issue 761: Add Profiling for Server Side Diagnostics

mofacts/client/views/experiment/unitEngine.js
if setspec.hintsEnabled == true OR stims.display.hintsEnabled == true : hints enabled
if setspec.hintsEnabled == true AND stims.display.hintsEnabled == true : hints enabled
if setspec.hintsEnabled == false AND stims.display.hintsEnabled == false : hints disabled
In Stim Display:
In TDF Setspec:
=> Iss1037: Added parameters for hintlevel triggers

mofacts/server/methods.js
Files were being listed multiple times for the data download. Added code that removes the duplicates
=> Issue 1040: Multiple copies of survey occur on download

custom_packages/meteor-accounts-saml-iis-version-2-10-2020/package.js, mofacts/.meteor/packages, mofacts/.meteor/versions, mofacts/client/index.html, mofacts/client/index.js, mofacts/client/lib/router.js, mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/instructions.html, mofacts/client/views/experimentReporting/studentReporting.js, mofacts/client/views/experimentSetup/contentUpload.html, mofacts/client/views/home/profile.html, mofacts/client/views/home/profileAudioToggles.html, mofacts/client/views/home/profileSouthwest.html, mofacts/client/views/home/profileSouthwest.js, mofacts/client/views/test.html, mofacts/client/views/turkWorkflow.html, mofacts/client/views/userAdmin.html, mofacts/package-lock.json, mofacts/package.json, mofacts/public/styles/main.css
Upgrades MoFACTs to Bootstrap 5.2 and replaces unsupported glyphicons and JQuery calls.
=> Iss996: Migrate to Bootstrap 5 Engine

mofacts/client/views/home/profile.js
only display speech api key setup for teachers/admin
closes #1055
=> issue 1055: Speech recognition interface not working

mofacts/client/views/login/signIn.js, mofacts/client/views/login/signInOauth.js, mofacts/client/views/login/signInSouthwest.js, mofacts/client/views/login/signUp.js, mofacts/startup.sh
sign out user before they send a sign in request
closes: #1057
=> Issue 1057: Prior logins stored and not cleared upon new login attempt

mofacts/client/index.js, mofacts/client/views/experiment/card.js, mofacts/client/views/home/profileAudioToggles.html
=> Iss1056 added different verbage

mofacts/client/index.html, mofacts/server/methods.js
=> Iss88: added email to user and admin with error report

mofacts/collections.app-test.js, mofacts/package-lock.json, mofacts/package.json, mofacts/run_meteor, mofacts/run_meteor_test
fixes #89 
every time run_meteor is called, unit_server.xml will have the output from unit tests as described in the collections.test.js
=> Iss89: added unit testing for server collections

mofacts/client/index.js, mofacts/client/views/experiment/card.js, mofacts/client/views/home/profile.js, mofacts/server/methods.js
track session ID to make sure redirects happen correctly
closes #1054
=> Issue 1054: Redirect not quite working right

mofacts/client/index.html
=> Add home button back in to staging

mofacts/client/views/experiment/unitEngine.js
fixed tdfs not being set in session on experiments
=> Issue 1082: Experiment crashes at optimized practice unit

mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/instructions.js, mofacts/server/methods.js
audio file upload and playback now supported
show continue button on instructions according to current unit number
Button trials with studies would crash the trial, fixed now
some bootstrap visual bugs present. 
closes #1084
=> Issue 1084: Failure in music demo

mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/instructions.html, mofacts/client/views/experiment/instructions.js
fixed continue button not showing at right times
=> Issue 1086: Lockout units have bugs on staging

mofacts/client/lib/router.js, mofacts/client/views/experimentReporting/dataDownload.html, mofacts/client/views/experimentReporting/dataDownload.js, mofacts/client/views/experimentSetup/FileManagement.html, mofacts/client/views/experimentSetup/FileManagement.js, mofacts/client/views/experimentSetup/contentUpload.js, mofacts/client/views/experimentSetup/tdfAssignmentEdit.js, mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js, mofacts/server/experiment_times.js, mofacts/server/methods.js
Added uploaded file management page
File uploaders (owners) can:
- Overwrite Stim and TDF files
- Assign Accessors
- Download related data
- Assign chapters
- Transfer ownership of Stim and TDF files
- Delete Stim and TDF files
File Accessors can:
- Download related data
- Assign Chapters
Data can only be downloaded from the current logged in user's classes or if the data doesn't originate from a class.
=> Issue 902: Download Data Specificity

mofacts/client/index.html, mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js, mofacts/client/views/new_templates/navigation.html, mofacts/public/styles/classic.css, mofacts/public/styles/neo-dark.css
=> Iss1050-3: UI updated

mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/instructions.html
Fix study answer not being shown
Fix continue button flakeyness
Closes #1095 #1096
=> Issue 1095 & 1096

mofacts/client/index.html, mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js
Removed Jquery script tag that was breaking TDFs.
=> Issue 1100: failure on start 

mofacts/client/views/experimentSetup/FileManagement.js, mofacts/client/views/experimentSetup/contentUpload.html, mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
Better stability in the file manager window for Stim file lesson names
Fixed stims not being able to be overwritten in file manager
Package upload button now functions similar to TDF and Stim upload buttons
Images are now able to be updated on subsequent package overwrites
Fixed ZIP file downloading
Removed Tooltip for card text response
closes #1104
=> Issue 1104: Countries Test: No images, no countdown

mofacts/client/lib/router.js, mofacts/client/views/experiment/card.js, mofacts/server/methods.js
Experiment states weren't being updated when audio files were changed via file upload. Added logic to check for missing audio files in card and find updated files when necessary. 
closes #1102
=> Issue 1102: Music Demo Error

.provisioning_script.sh, mofacts/client/index.html, mofacts/client/index.js, mofacts/client/lib/router.js, mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js, mofacts/client/views/new_templates/experimentSettings.html, mofacts/client/views/new_templates/navigation.html, mofacts/client/views/new_templates/navigation.js, mofacts/client/views/new_templates/signIn.html, mofacts/public/styles/classic.css, mofacts/server/methods.js
fixes #1106 and implements more UI improvements
@imrryr The tdf selection box has been implemented, so this is a major UI change.
=> UI updates part 4

mofacts/client/views/new_templates/navigation.html
=> Iss1112: Navigation bar

mofacts/client/lib/router.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
Old stim items werent being overwritten properly.
=> Issue 1111: No images for some items

mofacts/client/views/experiment/card.js
fix audio not progressing on music demo
=> Issue 1115: Music Demo Report 

mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
=> Issue 1111: Alert uploader when overwriting a file could break experiments.

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js, mofacts/server/methods.js
Added count to track number of items seen including study trails. Count can be reset as specified by TDF. 
Study trial outcomes are recorded as blank in history
closes #1120
=> Issue 1120: Bug in study recording

mofacts/client/lib/router.js, mofacts/client/views/experiment/instructions.js, mofacts/client/views/experiment/unitEngine.js
cardIndex, whichStim, whichHintLevel would not initialize previously if there was no unit instruction in a unit prior to them. 
closes #1116
=> Issue 1116: Psyc 7302

mofacts/client/views/home/profile.js
fixes #1123, adds check for nonexistant tags
=> Iss1123: checks for the existence of tags in search

mofacts/client/lib/router.js, mofacts/server/methods.js, mofacts/server/publications.js
Publications were sending too much data. Limited to only required data
Fixed syllable generation breaking on nonenglish stimuli
=> 1128: Arabic Test

mofacts/client/lib/router.js, mofacts/server/publications.js
Experiments werent properly subscribed to the required Tdf.
=> Issue 1139: Login fails

mofacts/server/methods.js
Package upload had out of date code that was causing stims to not fully upload
=> Issue 1103: Croatia Test Error

mofacts/client/views/experiment/unitEngine.js, mofacts/server/conversions/convert.js
=> Issue 1143: Study trial does not work and get stuck on first trial 

mofacts/client/lib/router.js, mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/dialogueUtils.js, mofacts/client/views/experiment/instructions.js, mofacts/server/methods.js, mofacts/server/publications.js
Unit can now shortcut instructions page if there are no instructions or lockout provided.
=> Issue 1141: Doesn't resume at beginning 

mofacts/server/methods.js
fixed stim files not uploading
=> Issue 1150: Stims file uploading issue

mofacts/server/methods.js
clearCurUnitProgress function was broken. Fixed now.
I pulled the latest data from the database and tested the TDF. Seemed to go through the TDF without issue locally.
=> Issue 1156: The stimuli do not appear after instruction

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/lib/router.js, mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js, mofacts/client/views/home/profile.js, mofacts/run_meteor, mofacts/server/methods.js
rollback experiment state changes to fix memory issue.
=> Issue 1160: Blank page for survey questions

mofacts/client/index.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js
old unused code was generating the error.
=> Issue 1146: Bugs in logic.json

mofacts/client/views/experiment/card.js, mofacts/server/methods.js
fix images not loading in unitinstructions
fix asset files not being assigned a stimulisetid on first upload
=> Issue 1165 & 1166: Can't load images correctly & Can't load audio sounds

mofacts/client/index.js, mofacts/client/lib/router.js, mofacts/client/views/experiment/card.js, mofacts/client/views/home/profile.js, mofacts/client/views/home/profileDebugToggles.js, mofacts/client/views/new_templates/signIn.js, mofacts/server/methods.js
Fix login breaking when using the enter key to submit login
Fix experiment issue
Fix publications
=> Issue 1164: experiment links not working

mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
alert user when overwritting files
=> Issue 1168: Provide warning dialog if upload will require overwriting

mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/instructions.js, mofacts/client/views/home/profile.js, mofacts/server/methods.js
File links were not being properly set on upload due to tdf/stim files being uploaded before image files, this caused the old image files to get linked to new tdf/stim files. To fix this we don't update the link on upload but on client when viewing the experiment. 
Updated tips and instructions logic to find image link on client like how card does.
=> Issue 1176: Images not appearing properly

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js
implement a ready prompt string to display between trials. 
In a TDF's delivery params add the display string as `readyPromptString` and the display time as `readyPromptStringDisplayTime`
=> Issue 128: Ready Prompt String

mofacts/client/lib/router.js, mofacts/client/views/experiment/card.js, mofacts/server/methods.js, mofacts/server/publications.js
Subtdfs were being overwritten because all tdfs with the same stimuliSetId would get overwritten.
Subtdfs weren't being published on experiments that required them.
=> Issue 1188: Blank page after using root file

mofacts/server/methods.js
stimuli was not being attached to sub-tdfs properly
=> Issue 1191: Blank page for the tone learning experiment

.gitignore, Vagrantfile, mofacts/server/lib/AllenNLP.js, mofacts/server/lib/Paraphrase.js, mofacts/server/lib/Process.js, mofacts/server/methods.js
Allows for local authoring not using aolney's server with docker
=> ISS1126: Levels of Deployment

mofacts/server/methods.js
Stim syllables not updated across sub-tdfs.
=> Issue 1194: A window of hint errors

mofacts/client/views/experiment/card.js
Preloading audio files caused audio source error. Now we only load the audio source that we need when needed to prevent this.
=> Issue 1193: Getting stuck on Tone 4

mofacts/client/lib/router.js, mofacts/client/views/experiment/card.js
Made records of study trials less ambiguous by recording the outcome as 'study' and user input as blank.
=> Issue 1198: A bug in the Outcome column of the data file

mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.js
Added a submission lock to prevent a user from accidentally submitting their response twice.
=> Issue 1200: Extra Trial Repetition In Data Output

mofacts/server/methods.js
Downloading the root tdf will now download all data for root and child tdfs.
=> Issue 1197: Root tdf download

mofacts/client/views/experimentSetup/contentUpload.html, mofacts/common/Collections.js
=> Iss1210: change wording on package uploader (staging)

mofacts/client/lib/router.js, mofacts/client/views/adminControls.html, mofacts/client/views/adminControls.js, mofacts/client/views/new_templates/testlogin.js, mofacts/server/methods.js
- Test logins are now enabled by using the Admin Control Panel (Login > Admin Control Panel > Test Logins)
- Test logins, when enabled, are available at /testlogin
-  You may also automatically test login by using a url variable:  /testlogin?username=testusername
=> Iss1228: fixed logins, added more intuitive way to enable test logins

mofacts/client/lib/router.js, mofacts/client/views/new_templates/signUp.html, mofacts/client/views/new_templates/signUp.js, mofacts/private/versionInfo.json, mofacts/public/styles/classic.css
=> Iss1226: clean up sign up page

mofacts/client/views/new_templates/signIn.html, mofacts/client/views/turkWorkflow.html, mofacts/client/views/turkWorkflow.js, mofacts/server/turk_methods.js
Reimplements the Turk Management Functions
=> Issue 1216: Restore Turk functions

mofacts/client/views/experiment/unitEngine.js, mofacts/common/Collections.js, mofacts/server/methods.js
Replaces getProbabilityEstimatesByKCId with a more efficient aggregate pipeline for lower data transfer,, less memory usage.
I will create a similar change for staging
closes #1242
=> Iss1242: rewrite data query

mofacts/client/views/experiment/unitEngine.js, mofacts/common/Collections.js, mofacts/server/methods.js
=> Iss1242 / 1245 rewrite query staging

mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
Errors weren't being shown when the package uploader failed.
=> Issue 1247: New package upload fails

mofacts/client/index.js, mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/client/views/experimentSetup/contentUpload.html, mofacts/client/views/experimentSetup/contentUpload.js, mofacts/public/styles/classic.css
In tdf's setspec or unit add "uiSettings" tag with parameters:
-Display Review Timeout Settings
"displayReviewTimeoutAsBarOrText":  both | bar | text | false
-Display Ready Prompt Timeout Settings
"displayReadyPromptTimeoutAsBarOrText":  both | bar |text | false 
-Display Card Timeout Settings
"displayCardTimeoutAsBarOrText": both | bar |text | false 
- Display Timeouts during study
"displayTimeOutDuringStudy": true | false
- Display user answer at top of feedback display
"displayUserAnswerAtTop": true | false 
- Display user performance bar during study
"displayPerformanceDuringStudy":  true | false
- Display Correct Answer at center of the page during feedback
"displayCorrectAnswerInCenter":  true | false
-Display Only "Correct" or "Incorrect" for feedback, overriding settings. …
=> Iss1239: UI Customization for Card

mofacts/client/views/experimentSetup/contentUpload.html, mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
fixes #1252. A check box in the interface on file uploads toggles the option to receive only an email upon successful processing of a package.
=> Iss1252: email option for file uploads

mofacts/client/views/experiment/card.js
=> Iss1258: fixed uisettings logic

mofacts/client/views/experimentReporting/dataDownload.js
=> Issue 1259: Blank lines in downloads main

mofacts/server/methods.js
=> Iss488 staging: do not display tdfs where setspec.disableProgressReport is true

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experiment/unitEngine.js
New force spacing parameter was allowing all cards to be selectable by the selection function. Rewrote so that forceSpacing will set a minTrialDistance of -1 when true and 1 when false.
=> Issue 1261: Gives study trials during practice using survey question stims

mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
reset shuffleclusters on package upload when not doing so would cause issues
=> Issue 1277: Problem for bird stimuli

mofacts/client/views/new_templates/lessonSelect.js
Lessons would not show if Session.get('curClass') was not set
=> Issue 1279: Chapter 9 is not showing in my menu for practice

mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/client/views/new_templates/navigation.html
-useranswer + [timeout] will be displayed as response in the dataset
-stackChoiceButtons (true or false) in uiSettings will force a 1 column display of buttons for multiple choice.
-the study and the trials match styles
-the bar and the countdown text don't flash during cards. However, since this template reloads, its not possible for it to not flash between cards unless we remove it to the index template.
-the audio options are not accessible during study or trial.
=> Iss1239: UI Changes and Timeout dataset changes

mofacts/server/experiment_times.js
=> Issue 1297: The data download issue on main

mofacts/server/methods.js
Rewrote package uploader to combine both stim and TDFs prior to upload. Wrapped TDF/stim uploader in a promise to force the asset upload to fire after its completed.
=> Issue 1300

mofacts/client/views/experiment/unitEngine.js, mofacts/package-lock.json
=> Issue 1304: Filtering out selection options that don't exisit (prod)

mofacts/client/views/experiment/unitEngine.js
Prevent system from calculating probabilities on hints when hints cannot be used.
Prevent system from selecting hint level probabilities on hints that cannot be used.
Rewrote indices calculation for better readability
=> Issue 1304: Filtering out selection options that don't exisit

mofacts/client/lib/router.js, mofacts/client/views/experiment/unitEngine.js, mofacts/public/styles/classic.css
=> Iss1309: fix for sylalble lengths where there are none

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js, mofacts/client/views/new_templates/curStudentPerformance.js
=> Issue 1307 Staging: problem with "swapclusters" 

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js
Refactored cluster shuffle and swap functions for better readability.
Shuffle and swap were being performed at the same time causing swap to break.
=> Issue 1307: problem with "swapclusters"

mofacts/client/views/experimentSetup/contentUpload.html, mofacts/client/views/experimentSetup/contentUpload.js, mofacts/client/views/new_templates/lessonSelect.js, mofacts/server/methods.js
- Uploader now embeds the file name of the package in the tdf
- Content Management download button now downloads the package file for that tdf
- Content Management 2nd list removed
=> Iss1320: Simplified Content Management

mofacts/client/views/experiment/card.js, mofacts/client/views/home/profileAudioToggles.html, mofacts/client/views/home/profileAudioToggles.js, mofacts/client/views/new_templates/lessonSelect.js, mofacts/server/methods.js
Save TTS and SR user settings in mongo
Properly show and hide TTS and SR settings when options are toggles
=> Issue 1326: TTS and SR won't start 

mofacts/client/views/experiment/unitEngine.js
=> Iss1330: Limit probability calculation to the current unit

mofacts/client/views/experiment/unitEngine.js
=> Iss1329: Optimal Learning distance calculation change

mofacts/client/views/experiment/unitEngine.js
=> Iss1339: fix clusterlist for restricting prob calculations

mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/public/styles/classic.css
=> ISS1342 UI Changes

mofacts/client/views/experiment/unitEngine.js
=> Iss1343: Correct saved probabilities logic

mofacts/client/views/experiment/card.js
- p.overallStudyHistory: array of current student's study question history. 0 represents 'study' type questions, 1 represents 'drill' trype questions
firxes #1344
=> Iss1344: Add p.overallStudyHistory

mofacts/client/views/new_templates/lessonSelect.js
=> Iss1352: Fix lesson select filtering for classes

mofacts/client/views/experiment/card.js
=> Iss1349: Remove requirements for optional end unit paramter 

mofacts/client/views/new_templates/signIn.html, mofacts/client/views/new_templates/signIn.js
Fixed class login to show teacher emails when selecting teacher
Fixed test login to add test users to class sections when logging in to a class/section.
=> Issue 1355: Class login does not show teacher names

mofacts/client/views/experiment/card.js
=> Iss1357: fix middle feedback display issue

mofacts/client/views/experimentSetup/classEdit.js
If this link were more insecure, it'd need therapy 
*ba dump tsss*
I think this wins for smallest possible PR.
=> Iss1363: Fix insecure link generation

mofacts/client/lib/router.js, mofacts/client/views/experiment/card.js, mofacts/client/views/new_templates/signIn.js, mofacts/server/publications.js
Multitdfs's condition TDFs werent being published on experiment sign in. 
Typo fixes
=> Issue 1373: multitdfs aren't working

mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
-Skipstudy button appears for all trial types. 
-Skipped questions have mandatory short timeout, so the user isn't watching a question for the study timeout
- UserAnswer will appear as [skipped] and incorrect in the dataset.
- Any feedback that appears is replaced with "Skipped."
Fixes #1370
-condition counts were not being generated on upload. This has been fixed.
-in the future, if the condition counts are not found or erroneous, an error message will display in the content management screen.
=> Iss1366: actually implement skipping questions using skipstudy

mofacts/client/views/experiment/card.js
How to test: 
-Make sure feedback latency is reading correct when skip button is used.
-Make sure input is the selected answer, not [skip] or continueStudy
=> Iss1381: removed skip from data input field

mofacts/client/views/adminControls.html, mofacts/client/views/adminControls.js, mofacts/public/styles/classic.css, mofacts/server/methods.js
Color pickers and more descriptive options
Test by opening up the admin panel and toying with all the custom theme options.
#1378
=> Iss1378: Themeing engine UI improvements

mofacts/client/lib/plyrHelper.js, mofacts/client/views/experiment/card.html
Show question numbers on hover
=> Issue 1335: CogniVideo UX Features - Chapters

mofacts/client/lib/plyrHelper.js
To test:
run a video unit, you should see a countdown for the next question. It should update regardless of seeking behavior.
fixes #1334
=> Iss1334: added countdown progress bar for video unit

mofacts/client/lib/plyrHelper.js, mofacts/client/views/experiment/card.html, mofacts/public/styles/classic.css
To test
-run a  video unit and get to a question. Question should appear over video
Fixes #1333
=> Iss1333: Overlay questions over video

mofacts/client/views/experiment/card.js
=> Iss1389: Typo in loadbalancer

mofacts/.meteor/packages, mofacts/.meteor/versions, mofacts/client/views/experiment/card.js
=> Iss1389: fix sourcing of filename for root tdfs

mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
@imrryr  The signal of the results of the file upload were not being sent to the client. The client was recieving 'undefined' which broke the .link function.
=> Iss1397: fixed server promise not returning to client

mofacts/client/views/experiment/card.js
fixes #1402 
Boolean translations in cases doesn't work that way. You have to translate them beforehand.
=> Iss1402: Fixed Boolean Translation of UI Settings

mofacts/client/views/experiment/instructions.html, mofacts/client/views/experiment/instructions.js
Line 72 of instructions was Data().getTime(). This is not a function.
Closes #1404
=> Iss1404: Date is not a function.

mofacts/client/views/experiment/card.js
Switches do not work correctly when the input is falsey. Changing switches to If/Else fixes the issue.
=> Issue 1402: Feedback settings not working

mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/instructions.html, mofacts/client/views/experiment/instructions.js
The HTML template was set as an else:
If there is a lockout timer, display a lockout message, else display instructions.
Changed to:
If there is a lockout message, display a lockout message. If Instructions exist, display instructions.
Also:
Changes to where admins can skip lockout timers.
=> Iss1405: Changed lockout timer html logic

mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js, mofacts/client/views/new_templates/lessonSelect.js
Schedule was being regenerated every time a TDF was resumed. Added code to check for existing schedule before a schedule is generated. 
closes #1403
=> Issue 1403: Reloading assessment sessions for multiple choice causes wrong answer to be miss assigned on resume

mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js
p.clusterOutcomeHistory was being updated after the probability calculation function was run causing 4 trials to be run before the probability function could detect that 3 correct trials had been run. 
closes #1401
=> Issue 1401: Model issue for the last item assigned to the 3 consecutive correctness level

mofacts/client/lib/plyrHelper.js, mofacts/client/views/experiment/card.html
Add on end event listener to increment unit number and log end of video unit
=> Issue 1421: CogniVideo Experiment Video Page bugs

mofacts/client/index.js, mofacts/client/views/new_templates/signIn.js, mofacts/server/methods.js
We needed to ask Microsoft Azure for the permissions for an offline token.
This needs testing on a server, since I can't do it locally.
To Test:
-Login with Office 365 at memphis.edu
-Navigate to Mofacts
-Click the Login with Microsoft Button
Expected:
No prompt for logging in except to grant permission if not granted previously
=> Iss1324: SSO Passthrough

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js
Added support for button trials in learning sessions
Fixed practice time not recording correctly when user is expected to use skipstudy
=> Issue 1449: multiple choice is not working for a learning session

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experiment/card.js
Reworked resume to be more stable
Fixed error in shuffling
=> Issue 1433: Corrupted TDF execution

mofacts/client/views/experiment/card.js
Changed skipping to allow user to skip study without creating two logged actions.
=> Issue 1432: Problems with MC question recording

mofacts/client/lib/router.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/instructions.js, mofacts/client/views/experiment/unitEngine.js, mofacts/client/views/home/profile.js, mofacts/server/methods.js
Allow User to refresh mid trial and resume gracefully
=> Issue 1454: refresh put it in loading... state

mofacts/client/views/experimentSetup/contentUpload.js, mofacts/server/methods.js
fixed stimDisplayTypeMap update to happen immediately
=> Issue 1457: Audio error for non audio tdf and stims 

mofacts/client/index.js
To test: 
try to make an error report without a description.
Fixes #1458
=> Iss1458: Check for error reports to have a description, otherwise reject.

mofacts/client/index.html, mofacts/client/views/experiment/card.html, mofacts/public/styles/classic.css
This was placed on index for some reason (I did it, just don't remember why).
The lower interaction container was blocking the buttons from being visible for small screen resolutions.
closes #1461
=> Iss1461: moved lower interaction back to card

mofacts/client/views/adminControls.html, mofacts/client/views/adminControls.js, mofacts/client/views/experiment/card.js, mofacts/server/methods.js
Skip study would incorrectly log a correct response once the skip button was pressed. Fixed it to only log the user input instead of the skip. 
Added a button to refresh the stim display type map for devs to use when importing dbs from mofacts/staging
=> Issue 1463: mofacts 2 problems with MC optimal learning

mofacts/client/views/experiment/card.js, mofacts/server/methods.js
study trials were not being recording practice time properly. Fixed to accommodate study times.
=> Issue 1163: Timer Unmatched

mofacts/client/views/experiment/card.js
clusterIndex and shufIndex were being set to both be the shuffled Index. 
now shufIndex gets set to the index of the stim item in the schedule and stimFileIndex gets set to the index of the stim in the stimulus file
=> Issue 1477: CF (Stim file index) not recorded

mofacts/server/conversions/convert.js
Stim file seemingly had invisible unicode characters. When uploaded this caused the invisible unicode characters to only appear in the data download. Added cleaner function to remove any invisible unicode
=> Issue 1476: CF (Correct Answer) output column contains characterset issues

mofacts/client/index.js, mofacts/client/views/experiment/card.js, mofacts/client/views/home/profile.js, mofacts/server/methods.js
Removes unsupported user profile calls.
=> Iss1446: Remove usage of User().profile where needed.

mofacts/client/views/home/profile.html, mofacts/client/views/turkWorkflow.html, mofacts/client/views/turkWorkflow.js
Combines AWS User Page and MTurk page
=> Iss1475: Rewrite Mechanical Turk Interface

mofacts/client/lib/router.js
When the user navigates to an experiment page force them to login again with their amazon turk id. This would ensure that there are no more instances of a user logging in twice causing weirdness with the experiment
=> Issue 1474: Mofacts 2, no buttons on consent form

mofacts/server/methods.js
Fixed settings on testing environment. Also added a check for attached files when content generation fails. Also adds some verbosity for testing.
Fixes #1473  (For Now)
=> Iss1473: Fix Email System for Mofacts-Full

mofacts/client/views/experiment/answerAssess.js, mofacts/client/views/experiment/card.js
Removes the majority of the bind functions from mofacts allowing for faster debugging.
=> Issue 1470: Rewrite card function to make it more linear and efficient 

mofacts/client/views/login/resetPassword.html, mofacts/client/views/new_templates/signIn.html
=> Iss1485: add sign forget button to front page

mofacts/client/lib/router.js, mofacts/client/views/new_templates/signIn.html, mofacts/client/views/new_templates/signIn.js
This adds an explicit continue button to experiment logins
=> Iss1486: This adds an explicit continue button to experiment logins

mofacts/client/lib/plyrHelper.js, mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/adaptiveQuestionLogic.js, mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/instructions.js, mofacts/client/views/experiment/unitEngine.js, mofacts/public/styles/classic.css, mofacts/server/methods.js
Beginnings of Adaptive Question Logic Module
Please peruse the top of the module to see the usage.
This will remain in draft for discussions until everyone agrees.
=> added adaptive logic evaluation module

mofacts/client/lib/plyrHelper.js, mofacts/client/views/experiment/adaptiveQuestionLogic.js, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js, mofacts/server/methods.js
adaptiveLogic tag in TDF is now json object where the key is the unit to be modified and the value is an array of all adaptive logic items
adaptive tag in TDF is now an array of ints where each value is a unit to be modified
adaptiveUnitTemplate tag in TDF is now array of ints to specify which templates to use for template building. 
added "AT" keyword to adaptive logic to allow the tdf author to specify a time in seconds to display the stimulus at (video units only)
various fixes to adaptive logic
=> Issue 1492: Modify multiple units with one unit through adaptive logic

mofacts/client/views/experiment/card.js
=> Issue 1496: Button trials not working

mofacts/client/index.html, mofacts/client/index.js, mofacts/client/views/home/profile.js, mofacts/client/views/new_templates/curPageNumbers.html
Adds page numbers to the top of the page. 
Enable in setspec with "showPageNumbers: True|False"
=> Issue 1491: add page numbers

mofacts/client/lib/sessionUtils.js
clear showPageNumbers on cleanup
=> Issue 1491 2

mofacts/client/views/home/profile.html, mofacts/client/views/home/profile.js, mofacts/server/methods.js
add check for spacy api and if not available then dont display the content generation button
=> Issue 1493: Content creation button

mofacts/.deploy/autobuild.sh
update autobuild script to present last 5 commits in an array that is easily parse-able
=> Issue 1506: Last 5 commits

mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js
Feedback was being displayed under stimulus fixes #1500
=> Issue 1500: Correct/Incorrect Feedback Not Displaying

mofacts/client/views/experiment/card.js
fix curUnit not being set between pages
=> Issue 1510: Error between units for adaptive units

mofacts/client/views/experiment/card.js
=> Issue 1512: Buttons in learning session

mofacts/client/views/experimentSetup/contentUpload.html, mofacts/client/views/experimentSetup/contentUpload.js
=> Iss1513: Allow admins to view other's content by toggle

.provisioning_script.sh, Vagrantfile, mofacts/client/lib/router.js, mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/public/styles/classic.css
"uiSettings": {
"displayConfirmButton": true
}
true:  allows the participant to click a selection (button or text input) and change their choice before clicking a continue button.
default: false
fixes #1513
=> Iss1518: Confirm Button for Cards

mofacts/client/lib/plyrHelper.js
take user out of fs mode for questions and return them after answer. disable rewinding to see old questions
=> Issue 1521: Questions not displaying in fullscreen mode

mofacts/client/views/experiment/card.html, mofacts/client/views/experiment/card.js, mofacts/client/views/experiment/unitEngine.js
Added modal popup that warns user when they are on the last unit.
Todo: add setspec to enable/disable and to define text shown to user, clean up visuals, create support for adaptive learning i.e. creating a unit after the "last" unit.
=> Issue 1487: Numbering Video Pages

Vagrantfile, mofacts/client/views/experiment/adaptiveQuestionLogic.js, mofacts/client/views/experiment/card.js
allow scheduling template units between defined units
=> Issue 1525: Units after unit template

mofacts/client/lib/router.js
Fixes #1533
TDF publications were not waited on for content management page
=> Iss1533:  Fix TDF Publications

mofacts/client/views/experiment/card.js
Fixes #1535 ,
The order on line 1462:   userAnswerFeedback(userAnswer, isTimeout , isSkip , simAnswerCorrect);
The correct order for   userAnswerFeedback(userAnswer, isSkip , isTimeout, simAnswerCorrect);
=> Iss1535: userAnswerFeedback had parameters backwards

mofacts/server/methods.js
=> Issue 1532: All data download button dowloads file with 2 identical copies of the data

mofacts/client/views/experiment/card.js
newUnit was being updated before we evaluate the adaptive units
=> Issue 1541: Basic video unit TDF is not opening and adaptive unit is not progressing to videos

Vagrantfile, mofacts/client/lib/plyrHelper.js, mofacts/client/lib/sessionUtils.js, mofacts/client/views/experiment/card.js
Refactor plyr to help with code changes and making the seeking functionality more consistent
re-enables seeking backwards to show previous questions and fix inconsistencies
Fix showing wrong stimuli
=> Issue 1522: seeking in plyr and displaying stimuli is inconsistent

mofacts/client/views/new_templates/signIn.js
=> Issue 1545: Bug in login for class, and content does not show though assigned to the class

mofacts/server/methods.js
remove instructions from instructor reporting
=> Issue 1549: Score is incorrect

mofacts/client/views/new_templates/studentReporting.js, mofacts/server/methods.js
Check that the user has data that can be shown in the progress reporter before trying to render progress report
=> Issue 1550: Screen shows attempt at progress reporting, but it only applies to learning session results

mofacts/client/lib/router.js
log out user before class login
=> Issue 1555: Class link is flaky

mofacts/client/lib/currentTestingHelpers.js, mofacts/client/views/experiment/answerAssess.js
add delivery param for enabling branched answers
set 'branchingEnabled' to true in deliveryParams to enable branching
=> Issue 1557: Text rendering in MC questions (only for correct answers)

mofacts/client/views/home/profile.js, mofacts/client/views/new_templates/lessonSelect.js, mofacts/client/views/new_templates/signUp.js, mofacts/server/methods.js
fixed users having to fully relog in order to see newly assigned tdfs
fixed sign up button not setting login params appropriately
fixed cases where login params are not set before they're read
=> Issue 1559: Failure of posting content

mofacts/server/methods.js
Expected Behavior:
In the content manager, admin users may click the minus button next to  a tdf to delete it.
=> Iss1564: admins may delete any tdf

mofacts/client/views/userAdmin.js, mofacts/server/methods.js
set Meteor.user() and Meteor.userId() to allow user impersonation.
=> Issue 1566: Impersonate User doesn't set Meteor.userId() properly

mofacts/client/views/userAdmin.html, mofacts/client/views/userAdmin.js, mofacts/server/methods.js
rename saveUserFile to insertNewUsers
=> Issue 1571: saveUsersFile Method is ambiguously named 

mofacts/.eslintrc.json, mofacts/client/views/experiment/card.js, mofacts/client/views/new_templates/signIn.js, mofacts/client/views/new_templates/testlogin.js, mofacts/common/Collections.js, mofacts/server/experiment_times.js, mofacts/server/methods.js, mofacts/server/methods.test.js
=> Issue 1582: Get rid of LoginTimes and utlQuerytimes colelction
