memphis-iis/mofacts

mofacts/client/lib/router.js
mofacts/client/lib/sessionUtils.js
mofacts/client/views/experiment/card.js
mofacts/client/views/home/feedback.html
mofacts/client/views/home/profile.html
mofacts/client/views/home/profileDialogueToggles.html
mofacts/client/views/home/profileDialogueToggles.js

Initial solution for #242, Move dialogue feedback type selection widget to interstitial before tdfs with dialogue enabled and allow feedback type choice enabled.

Issue 242: Move dialogue feedback type selection widget to interstitial before tdfs with dialogue enabled and allow feedback type choice enabled

---

mofacts/client/views/experiment/card.js
mofacts/client/views/home/profile.js

#239 
-Added ability for button based questions to have their buttons read by TTS
-Added check for if button responses are buttons or images.
-Added alert to notify user if their configuration is not supported by the selected TDF
-Bugfix: Fixed bug where questions were not being read if audio prompt mode was set to just "question"

Issue 239: Voice buttons and TTS buttons

---

mofacts/client/views/experiment/unitEngine.js

Added check for if stim has been introduced to the user before incrementing trialsSinceLastSeen.
Corrected saveComponentState calls.
Since trialsSinceLastSeen has to be initialized to 3 for probability calculations the database will show 3 for all stims that haven't been seen, but now that field won't be incremented. 
closes #270

Issue: 270 Incorrect trialssincelastseen in componentstate

---

mofacts/run_meteor

#310 
Please don't close 310, as this is an ongoing issue related to the Let's Encrypt! September 30th Expiration that is effecting meteor and nodejs distributions.

temporary fix for #310

---

mofacts/client/views/experiment/answerAssess.js
mofacts/client/views/home/profileDialogueToggles.js
mofacts/client/views/home/profileSouthwest.html

closes #309 
-Fixed capitalization that was causing refutational feedback to not show
-Moved feedback settings to interstitial as it is in the non-southwest version
-Made feedback settings persistent.
Note: If you want the user to set a feedback type then the Tdf file must include `"allowFeedbackTypeSelect": "true"` in the unit's delivery params.

Issue 309: Refutation doesn't work

---

mofacts/client/index.js

Fixes behavior of #394. Wiki button will now open new tab, and only be available on /profile

Issue 394: change wiki button behavior

---

mofacts/client/lib/router.js
mofacts/client/views/experiment/card.js
mofacts/client/views/experiment/instructions.js
mofacts/client/views/home/profile.js

Added session variables to check if current unit instructions have been seen in this session. If not, then it will show the instructions and the feedback settings. 
Added check to prevent loading of feedback settings window multiple times if it has been set for the current unit. 
Fixed bug with feedback settings not loading from history properly. 
Closes: #396 #391

Issue 396: Bug with Feedback Settings

---

mofacts/server/methods.js

MongoDB was returning data type `cursor` that Meteor cannot pass to the client. This change fixes that. 
closes: #363

Issue 363: Progress report doesn't appear for instructor reporting button

---

db/initTables.sql
mofacts/client/lib/currentTestingHelpers.js
mofacts/client/lib/sessionUtils.js
mofacts/client/views/experiment/card.html
mofacts/client/views/experiment/card.js
mofacts/common/Definitions.js
mofacts/private/tdf/testTdf.json
mofacts/server/methods.js
mofacts/server/orm.js

Added the new option for drill trials that allows users in a learning session to self pace. 
- CF_Self_Paced_Pretrial: the time between start of a trial and the user clicking to begin audio playback
- CF_Self_Paced_Posttrial: the time between answering a question and the user clicking to begin second audio playback (defaults to -1 on correct answer or in assessment sessions or if `allowuserdelayaudioplayback` is false)
- New data points do not effect the current timestamps.
- allowuserdelayaudioplayback: default false
allows user to select when they want to hear the audio file for a trial pre and post trial. 
closes #185

Issue 185: New Option for Drill Trial

---

mofacts/client/views/experiment/answerAssess.js
mofacts/client/views/experiment/card.js
mofacts/package-lock.json
mofacts/package.json
mofacts/server/lib/CachedElaboratedFeedback.js
mofacts/server/methods.js

Refutation now works. System will try to load from elaborated feedback cache first and then the glossary second. 
There is a bug with the countdown timer causing refutational feedback to disappear during the countdown. Disabling that feature until issue is resolved. 
closes #455

Issue 455: Refutation not working

---

mofacts/client/views/experiment/unitEngine.js

Meng's tdfs have no hintlevel defined, so to make extra sure that we don't accidentally trigger the error.

Issue 457: hotfix added for meng's tdfs

---

mofacts/client/views/experiment/card.js

Added a check before the tts call that will prevent tts playing on pages other than 'card', 'experiment', and 'instruction'
closes #445

Issue 445: Trial isn't completely ended after home button

---

mofacts/client/lib/currentTestingHelpers.js
mofacts/client/views/experiment/card.js
mofacts/private/tdf/exampleTDF.json

Added `refutationstudy` delivery param. If a user triggers a refutational dialogue, the system will use the time specified in `refutationstudy` rather than `reviewstudy`. Otherwise it will continue to use `reviewstudy`
closes: #470

Issue 470: Refutation and simple feedback need different times

---

mofacts/client/views/experiment/card.js
mofacts/client/views/experiment/unitEngine.js

#468 
whichStim and whichHintlevel were not being passed, which even if it is not required by the tdf, the selectNextCard function requires them  at start. The default is now 0.

Iss468: whichStim wasn't being defined for new engine

---

mofacts/client/views/experiment/unitEngine.js

debugLog was not being logged to console for each hintlevel, but for each stim where hintlevel = 0.

Hotfix: added logic for hintlevel debug output

---

mofacts/client/views/experiment/unitEngine.js

fixes #485,
p.hintsylls was still being called to display cloze answers, but this was moved outside of the probability function previously. It was an unnecessary check, as we should be checking if the answer is in the syllable dataset. 
also, the hint probabilities of every stim were being sent to the selection function, therefore setting the hint level to odd numbers, in this instance, hintlevel 13.
testing: run a trial with syllable data, it now displays hints properly and with the correct amount of syllables.

Iss485: hint sylls not being displayed.

---

mofacts/client/views/experiment/unitEngine.js

Time was being recorded on the stim and card level causing recorded time to be double what the actual time was. 
Changed the time reporting to only record on stim level.

Issue 491: Total time in instructor report incorrect

---

mofacts/client/views/experiment/unitEngine.js
mofacts/client/views/experimentReporting/studentReporting.js
mofacts/server/methods.js

Fixes #496 
-answers now show the appropriate number of blanks
-questions that have more than one blank grouped together are treated as one instance of an answer
-answers with 2 or less syllables display no hints
unrelated:
-calculations for progress report are now accurate, the meteor function was returning strings which had to be parsed to float.
-meteor function now correctly returning amount of stims seen.

Iss496: fixed issues with answer displays

---

mofacts/client/views/experiment/answerAssess.js

fixes #502 
-the answer was being evaluated by the difference between the inputed answer and the expected answer, not the hint + inputed answer and the expected answer.
i.e.: 
hint: nerv___ _____.
input: ous system.
answer comparision: ous system and nervous system
expected: nervous system. Return false
instead of:
answer comparison: nerv + ous system and nervous system
expected nervous system: Return true

Issue 502: fixed incorrect response for only entering missing syllables

---

mofacts/client/views/experimentReporting/studentReporting.html
mofacts/client/views/experimentReporting/studentReporting.js
mofacts/private/tdf/testTdf.json

Fixes #467 
- parameters are customizable using progressReporterParams in setspec. 
- "progressReporterparams": [optimumDifficulty, amount of trials to use as history for difficulty, minimum trials to display mastery rate,  amount of trials to use as history for mastery rate, minimum trials to display estimated mastery duration, amount of trials to use as history for mastery time estimate]
- Defaults to Array [0.7,30,60,30,90,60]
- The Items Mastered Graph will display total items introduced over all trials, not limited to trials in history.

Iss467: Extensive progress report 

---

mofacts/client/views/experiment/unitEngine.js

#514 changed display of answers
-multi word answers will no longer have blanks added after the first word if it is matched to the first word of the answer.

Issue 514: completed words have spaces after in answer

---

mofacts/client/views/experimentReporting/dataDownload.js
mofacts/server/methods.js

3 separate issues in this PR:
1. `getStudentPerformanceByIdAndTDFId()` had a bad querey that was causing data to be quadrupled or quintupled. This data was being reflected in the index bar
2.  Since we store correct/incorrect answer data on both cluster and stim level for probability calculations the `getStudentPerformanceForClassAndTdfId()` funciton had a querey that would retrieve the sum of answer data from both levels causing data to be doubled
3. changed the tsv extension to txt
closes #516

Issue 516: Data downloads, progress report, and teacher reports all report differently for Mike

---

mofacts/client/views/home/profile.html

Audio toggles were being assumed to exist on the page. Added them to the page. 
closes: #509

Issue 509: Test User Not Working

---

mofacts/client/views/home/profileSouthwest.js

Added back southwest icons to 557, was removed because of debuging over the storm
Fixes #557

Iss557: added back in southwest icons

---

mofacts/client/views/experiment/card.js

There was no check for if Speech to Text was enabled. If there was an API key entered the system had assumed that STT was on. 
closes #584

Issue 584: Weirdness with the stability of the settings (From Liz)

---

mofacts/client/views/experiment/card.js

The incorrect answer timeout was firing after navigation away from a page causing instructions page to become blank after a time. 
closes #579

Issue 579: Back button in browser should not give blank screen

---

mofacts/client/views/experiment/card.js

Fixes #605, changes unit check to where it compares the last unit completed to the length of the units, it was set to comparing the current unit to the length of the units, resulting in false completion.

Issue 605: Change unit end check

---

mofacts/server/methods.js

Query in datadownload was returning multiples of the same data. Changed query to include "distinct" tag to only show unique entries. 
closes #628

Issue 628: Duplicate items in data download

---

mofacts/client/views/experiment/card.html
mofacts/server/methods.js

getHistoryByTDFfileName method was bundling tdfs that used the same stim file. Causing data to multiply by the number of tdfs that share a stim. 
closes #655

Issue 655: data is still doubled

---

mofacts/common/Definitions.js

Review Latency was replaced with Feedback Latency. Updated definitions and db to reflect this. 
closes #704

Issue 704: CF (Review Latency) blank

---

mofacts/client/lib/currentTestingHelpers.js
mofacts/client/views/experiment/unitEngine.js

Index progress (At top of screen) was reporting different from the progress report and would change on refresh. I had accidentally left in some code that would exclude the dropped items from the index report. This fixes that issue. 
closes #717

Issue 717: Index display different from instances

---

mofacts/client/views/experiment/card.html
mofacts/client/views/experiment/card.js
mofacts/client/views/experiment/unitEngine.js

System was recording data incorrectly. If a stim that wasn't the first stim in a cluster was used the system would record it with the id of the stim that was the first in the cluster. 
This was causing the system to think that the user has only practiced up too the number of clusters in a chapter and never more. 
Also added quick testing buttons for answering correctly and incorrectly quickly. These are only available for admins and on development builds. Will not work on staging or prod. 
closes #720

Issue 720: Total introduced wrong in progress report

---

mofacts/server/methods.js

Distinct in sql is case sensitive, causing some answers to appear twice in the return when verifying the syllable count across postgres and mongo.

Syllable verification process was not accounting for case

---

mofacts/client/views/experimentReporting/studentReporting.js
mofacts/server/methods.js

Progress report wasnt counting questions that a user got both right and wrong in the past causing the estimated times to be displayed incorrectly. 
Progress report was also counting stims that aren't used in learning sessions, causing the estimated time to master all items to never be 0. 
closes #723

Issue 723: Mastery Time Estimate Wrong in Progress Report

---

mofacts/client/views/experimentReporting/studentReporting.js
mofacts/server/methods.js

Progress report was querying on component state for last `x` trials rather than history. This was causing the progress report to display some data on the last x number of stims in a set rather than on the last x trials
Closes #729

Issue 729: Progress report values wrong

---

mofacts/client/views/experimentReporting/instructorReporting.js

Date.getTime() returns a number type which doesnt have a function called `.isNaN()` so we have to run the global function `isNan()` on it to know if its NaN. 
Javascript can be weird. 
closes #736

Issue 736: Filter by date broken

---

mofacts/client/views/experiment/card.js

A user's start trial timestamp was somehow set to null or 0. Unable to reproduce. I added handling to catch if this happens again and notify the developers if it happens.
closes #742

Issue 742: Small glitch in instructor report

---

mofacts/client/views/experiment/card.js
mofacts/client/views/experiment/unitEngine.js

- Engine indices calculation now happen as soon as the user gives an answer. Next question handling happens based on whichever completes last between the review timeout and the indices calculations.
- There were some instances where we were calculating the minimum/maximum hint level probability multiple times for the same stim/cluster. This only happens once now after the next stim is selected and only if the stim can provide hints.
- We no longer calculate hint level probabilities when there is no way to give a hint. 
closes #746

Issue 746: Speedup the performing of calculations

---

mofacts/client/views/experiment/card.html
mofacts/client/views/experiment/card.js

Moved "Loading" div outside of the display. Only show loading if we are attempting to resume trial and the display is not ready. 
closes #766

Issue 766: "Loading..." displayed during trial

---

db/initTables.sql
mofacts/client/views/experiment/card.js
mofacts/client/views/experiment/unitEngine.js
mofacts/server/methods.js
mofacts/server/orm.js

Added DB column to component state that tracks how many correct and incorrect responses the user submitted for a session. This way we can track, on a session level, how many answers the user submitted. 
This column is cleared upon session completion. 
Setting maxTrials on a tdf's unit's delivery params will only effect that unit now. 
Also fixed the "answer correctly" button for debugging button trials. 
closes #751

Issue 751: Cant run back-to-back learning sessions

---

mofacts/client/lib/sessionUtils.js
mofacts/client/views/experiment/card.js

Google's Speech Recognition API does not support sample rates above 48kHz. Testing on a system using a higher sample rate would return nothing from the API call.
48kHz is the windows default sample rate so we'll force the system to use the most common sample rate. Mac/Linux users will not notice a different even though their default is 44.1kHz. Accuracy does not appear to be effected and users will not notice any latency unless they are using a much higher sample rate(not likely). 
Audio context is now closed on navigation away from card. Before, mofacts would navigate the user back to card if they had SR enabled and navigated away from a trial before the unit ended. 
closes #774

Issue 774: Force mofacts to sample at standard rate

---

mofacts/client/index.js

Computers running a version of safari before 15.4 cannot use the BroadcastChannel api as it was not implemented until 15.4
closes #778

replaIssue 778: Preventing new tabs breaks safari compatibility

---

mofacts/client/views/experiment/card.js

Commas were used to delimit the options for button trials on the unit level. 
Now either comma-delimited strings or arrays can be used to define distinct buttons.
closes #783

Issue 783: commas in stimuli buttons cause odd button multiplication

---

mofacts/client/views/experiment/card.js
mofacts/server/methods.js
mofacts/server/orm.js

TTS and SR api keys in TDFS used to be sent to the client where it could be leaked by users.
TDF TTS and SR api keys are now rewritten to true if they exist before being passed to the client. This way we preserve the key in the database without overwriting. 
TTS and SR calls are handled server side to hide the API keys. 
Note: user-submitted API keys are still on client side as they are only visible to the user that submitted the key. 
Closes #772

Issue 772: Remove TTS API key from client. 

---

mofacts/client/lib/sessionUtils.js
mofacts/client/views/experiment/card.js

Under certain conditions the recording lock would not release causing the lockup described in the bug report. 
Cleaned up the recording lock in event listeners and the session cleanup function to force the lock to be removed. 
closes #836

Issue 836: Audio input fails second time

---

mofacts/client/views/experiment/unitEngine.js

removed code that was unused and throwing errors. Still need to find root cause of errors in db. 
Response answers are given multiple response ID's instead of one unique. 
reworked component state loading to be more efficient
closes: #954

Issue 954: Practice resuming doesn't work at all

---

mofacts/client/views/experiment/unitEngine.js

outcome stack was being passed as a string and not array in some cases

Issue 969: function error

---

mofacts/server/methods.js

fixes #985 
-every time the server is restarted, it will create an email in the queue to go out with the error reports.

Iss985: add email to queue on deployment

---

mofacts/client/lib/currentTestingHelpers.js
mofacts/client/views/experiment/card.js
mofacts/client/views/experiment/unitEngine.js
mofacts/server/methods.js

add deliveryParam `resetStudentPerformance` to any unit where you want the user's displayed progress to be reset.
historical data is preserved.

Issue 1067: Reset score at start of unit

---

mofacts/client/views/experiment/unitEngine.js
mofacts/server/methods.js

shuffled clusters mapping wasnt being used when creating schedule

Issue 1065: Shuffleclusters not working

---

.gitignore
mofacts/client/views/experiment/card.js
mofacts/server/conversions/convert.js

Button choices were stored as strings in the database as an artifact of the postgres implementation. Changed them to be stored as an array directly as they are in the stim file.

Issue 1142: Extra Multiple Choice Options

---

mofacts/client/lib/currentTestingHelpers.js
mofacts/client/views/experiment/answerAssess.js
mofacts/client/views/experiment/card.js
mofacts/client/views/home/profile.js
mofacts/client/views/home/profileDialogueToggles.js
mofacts/common/Collections.js
mofacts/server/methods.js

Added refutation caching according to scenario 2 in #796 
- Student gets item wrong
- System checks cache
- Cache does not feedback for correct/incorrect answer pair
- Student receives simple feedback immediately
- Elaborated feedback is generated in background for this correct/incorrect pair and added to the cache

Issue 796: Cache building and saving system for refutations

---

mofacts/client/lib/currentTestingHelpers.js
mofacts/client/views/experiment/unitEngine.js

added clock based timer for practice time check
default is how mofacts has always worked
adding the delivery param `practicetimer` and setting it to `clock-based` will use the student performance's timer as the basis for if practice has completed.

Issue 1163: Timer unmatched

---

mofacts/server/methods.js

TDF search by experiment target was case sensitive but when passed to the client from the url would get lowercased.

Issue 1184: Login bug

---

mofacts/client/views/experiment/card.html

Study was set up only to display the answer on text stimulus. Fixed to support all stimulus types.

Issue 1185: Study trials don't show response

---

mofacts/client/lib/currentTestingHelpers.js
mofacts/client/views/experiment/card.js
mofacts/client/views/experiment/unitEngine.js

Added the delivery param "forceSpacing": 
- True (default): requires a minimum of 3 stimuli
- False: allows the unit to gracefully end when there are no available stimuli.

Issue 1249: Graceful termination when no available items

---

mofacts/client/views/experimentReporting/dataDownload.js

Hide tdf's that don't have units from the data download page

Issue 1259: Blank lines in downloads

---

mofacts/client/views/home/profileDialogueToggles.js

As a note, the term "simple" is only used once in reference to feedbackType. If left blank or undefined, feedbackType assumes default/simple
closes #1269

Iss1269: change simple feedback to default

---

mofacts/client/views/experiment/card.js
mofacts/client/views/experiment/unitEngine.js

Fix race condition causing overall outcome history to be recorded after trial is logged and next card is selected
Fix study trials being recorded in overallOutcomeHistory
Fix hintlevel calculations occurring redundantly

Issue 1283: OverallOutcomeHistory appears wrong (staging)

---

mofacts/client/views/experiment/card.js
mofacts/client/views/experiment/unitEngine.js

Fix race condition causing overall outcome history to be recorded after trial is logged and next card is selected
Fix study trials being recorded in overallOutcomeHistory
Fix hintlevel calculations occurring redundantly

Issue 1283: OverallOutcomeHistory appears wrong

---

mofacts/server/experiment_times.js

data download was failing because `undefined` and `"undefined"` are different

Issue 1297: The data download issue on staging

---

mofacts/client/views/experiment/card.js
mofacts/client/views/experimentSetup/contentUpload.html
mofacts/client/views/experimentSetup/contentUpload.js
mofacts/client/views/new_templates/lessonSelect.js
mofacts/server/methods.js

@imrryr 
setspec.loadbalancing ("max" | "mix" |  false, default false) - enables load balancing between experiment conditions. max selects the condition from any condition with participant counts lower than the condition with the largest participant count. Min selects the condition from any condition that has the least  participant count.
setspec.countcompletion ("beginning" | "end" | int unit number, default: error) - sets where the participant count iterates. Beginning increments the participant count when the condition is selected. End increments when the participant has finished all units in a root TDF. An integer unit number increments the participant count for the root TDF when the unit specified is started. Requires setspec.loadbalancing  to be true.
unit.countcompletion (true | …

Iss1319: Experiment Condition Randomizer

---

mofacts/client/views/experiment/card.js

Fixes #1348 
Looks like someone was being fancy with the triple equals sign. Tdfs should run with isButtonTrial as a string or a boolean.

Iss1348: fix strict equality in isButtonTrial

---

mofacts/client/lib/router.js

fixes #1361 
Microsoft requires that the request URL comes from http://staging.optimallearning.org, not a class URL. So, after setting the class session variables, we should redirect to the login url.

Iss1361: Redirect to login url after setting class session variables when using class url

---

mofacts/client/views/new_templates/signIn.js

To test:
-Use a Class URL
-Login with Microsoft
-Check if section map collection is populated
Fixes #1367

Iss13678: fix office365 login not setting section map data

---

mofacts/client/views/adminControls.html
mofacts/package-lock.json
mofacts/package.json
mofacts/server/methods.js

Fixes #1394 
This modification sends an email to each user mentioned as teachers, admins, or owner in initroles in settings.json. It will not send duplicates emails if the email is listed multiple times.
Bonus:
The readout for disk usage will be more accurate and in gigabytes. Showing block sizes is a bit unfriendly.

Iss1394: add emails to teachers and all admins on deploy

---

mofacts/client/views/experiment/card.js

Fixes #1393 
New Specs for UISettings @imrryr 
onlyShowSimpleFeedback ("onCorrect" | "onIncorrect" | true | false, default: onCorrect): Reduces feedback to just the word "Correct" or "Incorrect". This is controllable to trigger during correct response feedback using the "onCorrect" setting. Inversely, this can be set to "onIncorrect" to trigger only during incorrect response feedback. True enables both, and false enables neither setting. 
displayUserAnswerInFeedback  ("onCorrect" | "onIncorrect" | true | false, default: onIncorrect): This prepends the user answer in the feedback. This is controllable to trigger during correct response feedback using the "onCorrect" setting. Inversely, this can be set to "onIncorrect" to trigger only during incorrect response feedback. True enables both, …

Iss1393: UI Settings for more cutomizability

---

mofacts/client/views/experiment/card.js

Creates a clean exit when the expected new unit number is greater than the available units.
Fixes #1398

Iss1398: Clean exit of completed units

---

mofacts/client/lib/currentTestingHelpers.js

The delivery parameters were not being fully set correctly, resulting in forceSpacing to be false for Wei's experiment. The previous code was an odd way of setting the defaults and was pretty inefficient.
Closes #1401

Iss1401:  forceSpacing was not being set

---

mofacts/client/views/experiment/instructions.js
mofacts/server/methods.js

Lockouts stored in Meteor user profiles were being erased on logout. To make them persistent, they need to be stored at the top level of Meteor.user, not the profile.
Ref: https://guide.meteor.com/accounts#dont-use-profile
Fixes #1404

Iss1404: Meteor profiles are not necissarily persistant.

---

mofacts/client/views/experiment/instructions.js

tdf.setspec.recordInstructions = true | false | array [unit numbers], default false: tags the instructions page for recording duration in the history table. True triggers all instructions pages to be recorded, false tags no instructions pages to be recorded. An array of unit number integers may be passed to record certain unit number instructions ex. [1,2,3].
unit.recordInstructions = true | false, default false: tags this unit's instructions page for recording.
fixes #1413

Iss1413: Add instruction page history recording

---

mofacts/client/lib/router.js
mofacts/client/views/experiment/card.js
mofacts/client/views/experiment/instructions.html
mofacts/client/views/experiment/instructions.js

Having the lockout timer inside of a blaze template caused a race condition, so it was being set until this race condition was met. The new behavior sets the lockout once. 
If there is no lockout timer on record and the unit requires it,  it will bet set. We have to await the Meteor server side call or the lockout will not be set by the time the lockout timer starts.
Also, users returning from closing their browser will not be asked to log in again after their browser crashes. They are automatically redirected to the experiment.

Iss1404 3: Lockout Timers

---

mofacts/client/views/experiment/card.js

Unit type was not being set in time causing a race condition where `processUserTimesLog` would proceed as if it was on the previous unit. 
fixes: #1417

Issue 1417: Unable to deliver the Post-test unit after the lockout expires

---

mofacts/client/lib/plyrHelper.js
mofacts/client/lib/sessionUtils.js
mofacts/client/views/experiment/card.html
mofacts/client/views/experiment/card.js
mofacts/client/views/experiment/instructions.html
mofacts/client/views/experiment/instructions.js

Fixes #1428  (and others)
New Spec:
setspec.allowRevistUnit (true | false, default: false): Allows users to go back to units they have already visited. Users may go forward, because the continue button will be active on all previous units.
OR:
currentDeliveryParams.allowRevisitUnit (true | false, default: false): Allows users to go back to the immediately previous unit.  Users will only be allowed to go as far back as the last unit that has this set to true.
___
New Spec:
curTdfUISettings.displayEndOfVideoCountdown (true | false, default: false): If questions are not set in a video session, enabled the display of the time until the video finishes. If false: if no questions are set  this will hide the countdown.
[Screencast from 03-14-2024 11:23:26 …

Iss1428: Back and Forth Functionality

---

mofacts/client/lib/router.js
mofacts/client/views/experiment/card.html
mofacts/client/views/experiment/card.js
mofacts/client/views/experiment/instructions.html
mofacts/client/views/experiment/instructions.js
mofacts/client/views/new_templates/signIn.html
mofacts/client/views/new_templates/signIn.js

fixes #1419 and other verbal requests
1. Adds video text above the video unit's player.  
unit.videosession.displayText: ""  (default undefined, so not shown): Displays an HTML  text above the video player. Displays for the whole video.
2. Signin Customization for Experiments:
tdf.tutor.setspec.uiSettings.experimentLoginText: "" (default: "Amazon Turk ID": displays this text as the text placeholder for the signin box where participants log in to experiments
3.  Instructions title display
tdf.tutor.setspec.uiSettings. instructionsTitleDisplay (default: headerOnly, true, false):  Sets the instruction page's header behavior. Setting this to headerOnly will only display the word "Instructions". True will display the instructions header and the lesson name (new theme behavior). False will …

Iss1419: UI Settings and Video Text

---

mofacts/client/views/experiment/card.js

Submission lock was causing first action timestamp to not be recorded until the user uses the enter key.

Issue 1434: start and end latencys equal for typing task

---

mofacts/client/lib/router.js

Added a optional chaining operator (?) to allow this expression to return false if uiSettings doesn't exist.

Iss1453: allows for tdfs where uisettings is not set

---

mofacts/server/lib/AllenNLP.js

Allows Content Creation Endpoints to be set in Settings. Below are the defaults, which assume a docker deployment. For testing you can use iisml-precision-7920-tower.uom.memphis.edu:8002 and iisml-precision-7920-tower.uom.memphis.edu:8001 respectively
Meteor.settings.clozeAPIEndpoints{
allenNLP: 'allenNLP:8002',
spacy: 'spacy:8001'
}

Iss1303 mofacts full jun18

---

mofacts/client/lib/router.js
mofacts/client/views/new_templates/signIn.js
mofacts/server/methods.js

Incorrect TDF files were being used for experiments if they had similar experiment targets due to poorly written regex
experiment targets are automatically lower cased to help ensure matches

Issue 1495: Missing Unit

---

mofacts/client/views/experiment/adaptiveQuestionLogic.js

unittemplate will now be loaded from setspec.unittemplate[index].
Closes #1520

Iss1520: Change location of unittemplates to setspec

---

mofacts/client/views/experiment/card.html
mofacts/client/views/experiment/card.js

Fixes #1592 
For @shelbik37 the skip and continue buttons need to be configurable to display custom text (i.e. text in other languages 'continuar' in spanish, etc).
This is being merged into staging.
The spec will be in the UISettings and be configurable in tdfs by setting
'continueButtonText' - string expected - default: "Continue",
'skipStudyButtonText': - string expected - default: "Skip"
To test:
Upload a tdf with UI settings 'continueButtonText' and 'skipStudyButtonText'.

Iss1592: Continue and Skip Button Custom Text String

---

mofacts/client/views/experiment/card.js

Controls whether any feedback (correct/incorrect messages, etc.) is shown to the user after answering a question.
"suppressFeedbackDisplay": false
Boolean, default False
If suppressFeedbackDisplay is set to true, no feedback will be displayed to the user after answering.
If omitted or set to false, feedback will be displayed as usual.

UISettings: Supress feedback display

---

mofacts/client/views/experiment/card.html
mofacts/client/views/experiment/card.js
mofacts/public/styles/classic.css
mofacts/public/styles/dark.css
mofacts/public/styles/light.css
mofacts/public/styles/neo-dark.css
mofacts/public/styles/neo.css
mofacts/test/handleUserInputTest.json

fixes #1606 
This PR fixes the bug where image stimuli were appearing outside the stimuli box and adds comprehensive color customization options for the stimuli container.
- All stimuli types (text, images, videos) now appear within the same container
- Color customization works with both Bootstrap classes and custom colors
- Transparent mode properly hides the box background
- Backward compatibility maintained with existing configurations
Examples:
```json
{
"uiSettings": {
"showStimuliBox": true,
"stimuliBoxColor": "alert-light"
}
}
```
```json
{
"uiSettings": {
"showStimuliBox": true,
"stimuliBoxColor": "#ff6b6b"
}
}
```
```json
{
"uiSettings": {
"showStimuliBox": false,
"stimuliBoxColor": "alert-primary"
}
}
```

Iss1606, fixing stimuli container box and adding customization

---

mofacts/client/views/experiment/card.js

A bug in the equality check in handleUserInput where source was assigned instead of compared (single = versus triple === for strict equality)
handleUserInput was also missing the user input box DOM in the call
handleUserInput({}, "voice) should have been handleUserInput({answer: useranswer}, "voice")
GreekTest runs successfully on staging. Although you might want to check your font settings.
Fixes #1604

iss1604: correct comparison operator in handleUserInput and pass userAnswer in speechAPICallback

---

mofacts/client/views/experiment/card.js
mofacts/server/methods.js

This pull request simplifies how API keys are retrieved and used for Google Speech and Text-to-Speech (TTS) API calls. The main changes remove redundant code, centralize key retrieval logic, and ensure that API keys are consistently accessed via a single method.
Key improvements include:
API Key Retrieval Refactoring:
* Removed the standalone `getTdfTTSAPIKey` function and now use `methods.getTdfTTSAPIKey` for TTS API key retrieval, ensuring all API key access is routed through the `methods` object for consistency. [[1]](diffhunk://#diff-87be22a1bd2128a9a50980d9312385ceb66bb997b2139772a50556db2ab698d4L315-L320) [[2]](diffhunk://#diff-87be22a1bd2128a9a50980d9312385ceb66bb997b2139772a50556db2ab698d4L3407-R3401)
* Updated `makeGoogleSpeechAPICall` to always attempt to fetch the TDF-level …

Issue 1626: Speech recognition should respect embedded keys in every login flow

---

mofacts/client/views/experiment/card.js
mofacts/client/views/home/profile.js
mofacts/client/views/home/profileAudioToggles.js
mofacts/client/views/new_templates/lessonSelect.js
mofacts/client/views/new_templates/studentReporting.js

**audio mode refactor**
- SR toggle was being handled by a modal checkbox that wasnt visable to the system when TDFs were loaded causing the system to not enable it
- Switched this handle to checking user profile since that checkbox value would also be available on the user profile
**google api error reporting**
- Noticed that system wouldnt alert the user if there was a problem with their Google api key, eg: api key expired
- Added alert that paused experiment if system detects a problem with google api allowing user to fix or notify developers before logging bad experiment data

Issue 1625: SR wont start
